### ISSUE TITLE
Renaming PaymentApp* classes

### ISSUE THREAD

**Issue by tommythorsen** [w3c/webpayments-payment-apps-api#109]
Now that we've renamed to our specification to Payment Handler API, I think it would make sense to not name our classes starting with PaymentApp. I don't think it's super elegant to just rename everything to PaymentHandler*, so I'm looking at alternatives. The first classes I wanted to consider was the following:

```
5.2 PaymentAppManager interface
5.3 PaymentAppOptions interface
5.4 PaymentAppOption dictionary
5.5 PaymentWallets interface
5.6 WalletDetails interface
```

I think `PaymentAppManager` can just become `PaymentManager`, but `PaymentAppOptions` can not be renamed to `PaymentOptions`, as that would cause a name conflict with a class in the Payment Request API specification.

When talking about digital payments, one often talk about a digital wallet containing a set of digital payment instruments. So, how about `PaymentInstrument`? I realize it's a term with very specific meaning, but I think that it actually fits quite well here.

I would also suggest renaming `WalletDetails` to be consistent with the other names, so that we would end up with the following set of classes:

```
5.2 PaymentManager interface
5.3 PaymentInstruments interface
5.4 PaymentInstrument dictionary
5.5 PaymentWallets interface
5.6 PaymentWallet dictionary
```

WDYT?

**Comment by rsolomakhin** [comment]
SGTM

**Comment by pjbazin** [comment]
+1

III Pascal BAZIN<http://gsearch.gemalto.com/search/people/detailspeople.jsp?q=gin:10021956>

**Comment by adrianhopebailie** [comment]
I have an action to go through and fix this as soon as @ianbjacobs and @adamroach have finished the edits they wanted to make before the f2f.

@tommythorsen - If you're already working on it let me know.

**Comment by tommythorsen** [comment]
@adrianhopebailie: I am not working on this.

Are there major changes incoming? I was thinking to go through the respec warnings and sort those out at some point, but I don't want to create a lot of conflicts for people.

**Comment by ianbjacobs** [comment]
Hi @tommythorsen,

Let's wait for @adamroach's edits and then do a cleanup pass (e.g., early next week).

Ian

**Comment by adamroach** [comment]
I'm making these changes in my edits as well. It would be worthwhile for someone to come behind me and make sure I didn't miss anything. :)

**Comment by tommythorsen** [comment]
Most of this has been dealt with by https://github.com/w3c/webpayments-payment-apps-api/pull/113, but @adamroach: what's the point of the inconsistently named `WalletDetails`? Is there a good reason for choosing this name?

Can we either rename `WalletDetails` to `PaymentWallet` or `PaymentInstrument` to `InstrumentDetails` so that the names match?

**Comment by adamroach** [comment]
@tommythorsen -- Sorry, no real principled reason for having them different. Feel free to adjust them to be consistent.

**Comment by ianbjacobs** [comment]
Today we resolved [1] to harmonize using the convention of "Payment" as a prefix. Thus, we chose PaymentWallet and I'll update the spec accordingly.

[1] https://www.w3.org/2017/04/04-apps-minutes#item03

**Comment by tommythorsen** [comment]
Great! Since you have an action on you to make the change, I don't think we need this issue, so I'll close it.
