### ISSUE TITLE
What should be the user experience when an app is recommended for two methods?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#11]
Migrated from https://github.com/w3c/webpayments/issues/155 by @LaurentCastillo 

It can happen that a payment app will be recommended for two or more methods, both supported by the merchant. What should the UX be in that case:
-    Display app twice, with a different method each time?
-    Display it only once?
-    Anything else?

**Comment by tommythorsen** [comment]
I don't think the specification should care about this. We should leave the UX decisions up to the mediators to decide as much as possible. If we put too many rules down, then there will be less opportunity for innovation.

**Comment by ianbjacobs** [comment]
The consensus at the 3 Aug 2016 payment apps task force call is to not say anything (as suggested here by Tommy.

Ian
http://www.w3.org/2016/08/03-apps-minutes.html
