### ISSUE TITLE
Open Window Algorithm

### ISSUE THREAD

**Issue by tommythorsen** [w3c/webpayments-payment-apps-api#115]
This algorithm that I'm adding in https://github.com/w3c/webpayments-payment-apps-api/pull/106 is *very* similar to the Open Window Algorithm in the Service Workers specification (because I've copied and pasted most of it). Should we refer to the Service Workers specification instead of copying their steps?

The thing is, our algorithm is not exactly the same, so we might have to say something inelegant, like "run the open window algorithm, but skip step number four and set some value to the internal slot `[[windowClient]]` just before returning".

**Comment by marcoscaceres** [comment]
We can coordinate with the editors of the SW spec - so we don't need to monkey-patch it. We should reuse as much of their infrastructure as possible.

**Comment by ianbjacobs** [comment]
@romandev, do you have any interest in helping to reconcile the algorithms in Payment Handler and the Service Workers spec?

**Comment by romandev** [comment]
@ianbjacobs Thank you for comment.
I'm not sure if I can do it well but I'll try it.
Actually, I already tried it in another issue but it's not easy without changing SW spec's algorithm.
At first step, I'll talk to this issue with @jungkees. (He is my co-worker and SW spec editor.)

**Comment by ianbjacobs** [comment]
@romandev and @jungkees, thank you! We look forward to hearing back from you.

**Comment by ianbjacobs** [comment]
@romandev and @jungkees, any updates on your end on this issue?
Thanks!
Ian

**Comment by ianbjacobs** [comment]
@romandev, @jungkees, @rsolomakhin, can we close this issue?
Ian

**Comment by rsolomakhin** [comment]
@ianbjacobs: I don't think so. We should make the service worker's open window algorithm more generic and then re-use it in our spec. That's how browsers are most likely to implement this algorithm internally. Instead the spec currently has *almost* a copy of the algorithm from service worker, so an implementer has to carefully compare the two specs side-by-side to understand where they are different. That's sub-optimal.

**Comment by ianbjacobs** [comment]
@rsolomakhin, ok. I hope to chat about this with @marcoscaceres and @romandev face-to-face.

**Comment by romandev** [comment]
Hi all,

Is there someone who remebers why do we had to add `e.openWindow()` instead of using `clients.openWindow()`?

**Comment by dlongley** [comment]
@romandev,

> Is there someone who remebers why do we had to add e.openWindow() instead of using clients.openWindow()?

See #97 for the rationale.

**Comment by ianbjacobs** [comment]
Closing this issue which is now subsumed by #321.
