### ISSUE TITLE
[Editorial] Clean up respec errors

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#122]
Clean up respec errors (and probably run the spec through tidy) before FPWD

**Comment by marcoscaceres** [comment]
> probably run the spec through tidy

Must be run through tidy before EVERY merge. Otherwise, it's super hard to review and track changes and the document becomes a mess.

**Comment by ianbjacobs** [comment]
Closed by:
 https://github.com/w3c/webpayments-payment-apps-api/commit/a3f548241c09097d585ce3654f60de14ce590490
