### ISSUE TITLE
[Privacy] Clarify what information user agents forget at various moments

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#124]
For user privacy, should we include requirements that user agents "forget" information when certain events happen:
 * User unregisters a payment handler
 * User deletes a wallet or instrument

I am adding this issue based on a Privacy Interest Group review of Payment Request API (that mentions payment apps):
 https://lists.w3.org/Archives/Public/public-payments-wg/2017Apr/0007.html

**Comment by marcoscaceres** [comment]
Seems redundant, tbh. Calling the removal methods on the corresponding interfaces will cause deletion of that data (because the spec says so). It would be strange if user agents were keeping deleted things around.

**Comment by ianbjacobs** [comment]
@marcoscaceres, 

What you describe may well come to pass. I don't mind keeping this in as a reminder while the spec evolves.

**Comment by marcoscaceres** [comment]
I'd suggest closing... "if it ain't broke..." 

Otherwise, you just end up with a stack of things in the bug tracker that will just get marked as "postponed" and never actually get looked at.

**Comment by ianbjacobs** [comment]
Given Marco's assessment of what implementations will do upon delete, I am closing this for now.
