### ISSUE TITLE
Image object is undefined

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#125]
The "icons" field states:

 "The icons member is an array of image objects..."

but "image objects" are undefined here. The spec is clearly referencing the Web App Manifest term:
 https://www.w3.org/TR/appmanifest/#dfn-image-object

There is a lengthy section of that spec devoted to image objects. Should we:

 * Include a normative reference to that spec, or
 * Make use of a simplified data structure for our needs here

(I don't have an informed opinion yet.)

We've raised this issue after discussion at the 4 April 2017 payment apps task force call [1].

Ian

[1] https://www.w3.org/2017/04/04-apps-minutes#item07

**Comment by rsolomakhin** [comment]
Let's include a normative reference the algorithms for processing ImageObject. However, the manifest spec does not have WebIDL, so we would need to define it in our own spec.

**Comment by marcoscaceres** [comment]
We should probably start defining things as IDL dictionaries in the manifest spec - or else it's gonna get messy if other specs want to use this stuff.  It's ok if we work out the details here and then upstream what we come up with.

**Comment by ianbjacobs** [comment]
I believe this is closed with this PR merged:
 https://github.com/w3c/payment-handler/pull/174

Ian
