### ISSUE TITLE
Add .clear() to map-likes 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-payment-apps-api#129]
It be useful to have a `clear()` method for interfaces that store things.

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

With AdamR's guidance we added clear() methods for wallets and instruments along with other edits to align with your comments (which were mostly respect and xref fixes).

https://w3c.github.io/webpayments-payment-apps-api/#clear-method
https://w3c.github.io/webpayments-payment-apps-api/#clear-method-1

Ian

**Comment by ianbjacobs** [comment]
@marcoscaceres, does the current draft of the spec address your isssue?

Ian

**Comment by marcoscaceres** [comment]
Sort of, but not really (again, seems things were added in a rush to go to FPWD without wide review😢)... 

Why do we have two interfaces with identical method signatures? We should just have a single `AsyncDataStore` interface for `PaymentWallets` and `PaymentInstruments`.  That is:

```
    readonly attribute AsyncDataStore instruments;
    readonly attribute AsyncDataStore wallets;
```

We should really be talking to the IDB folks and aligning here on an interface. 

What is currently there is not clear because there is no real transactional semantics for what happens if:

```JS
Promise.all([x.add("1"), x.clear(), x.add("2")]); 
``` 

As they all run in parallel without an associated task queue.

**Comment by ianbjacobs** [comment]
Great comments. 

I found this link to the IDB editors' draft:
 http://w3c.github.io/IndexedDB/

I'm happy to take an action to talk to them about alignment.

Ian

**Comment by marcoscaceres** [comment]
Would be good. We need a primitive that is an domain specific database, but with a common interface that looks a lot like an  (async) map. We have also the Cache API for precedence here.

**Comment by ianbjacobs** [comment]
Update: after some feedback from Joshua Bell, Ali Alabbas, Rouslan Solomakhin, and Mike Smith, there seems to be some agreement that:

 * reusing an "async map-like" would be great, but
 * Async map-like  is neither defined nor implemented in any browsers

More input welcome here,

Ian

**Comment by adrianhopebailie** [comment]
As we have resolved to drop wallets this is no longer an issue. There is only a single collection interface defined.

**Comment by ianbjacobs** [comment]
Hi Adrian,

I'm reopening because there is a separate topic here which is redefining the (single remaining collection) in a way that aligns with "async map-like" that is being worked on (or potentially worked on) lower in the Web stack.

I want to confirm the viability of doing that. So far it does not seem that there is active async map-like stuff happening in WebIDL at this time. I would like to review this with Marcos before closing.

**Comment by adrianhopebailie** [comment]
> Async map-like is neither defined nor implemented in any browsers

Not sure there is anything left to discuss?

**Comment by ianbjacobs** [comment]
@adrianhopebailie wrote:

> Not sure there is anything left to discuss?

Perhaps not. I'm leaving open until we close the loop with @marcoscaceres.

**Comment by marcoscaceres** [comment]
I think what we have is ok for now.
