### ISSUE TITLE
Define event handler before payment manager

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#134]
Given the confusion around https://github.com/w3c/webpayments-payment-apps-api/issues/127 I suggest we switch the order of the content to start be defining and explaining the new event handler for 'onpaymentrequest'.

Following that we should define the addition of the payment manager to the Service Worker registration flow and how this is used by developers to express the capabilities of their payment handlers to the browser.

**Comment by ianbjacobs** [comment]
Can we close this new issue, which seems mostly about 127, and instead move your comments to 127?

**Comment by adrianhopebailie** [comment]
I think we can close #127 but happy to do either way
