### ISSUE TITLE
Passing modifiers to payment apps

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#139]
The API passes `total`, but not `displayItems` to the payment app. When it comes to `modifiers`, the data contains `additionalDisplayItems` as it's passed to the payment app. Should that element be cleared?

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin,

This seems correct, but is any change required to the specification? Looking at the Modifiers Population Algorithm [1], it seems that "supportedMethods" and "total" are explicitly passed,
which suggested to me that additionalDisplayItems is already not passed.

Do you read it that way?

Ian

[1] https://w3c.github.io/webpayments-payment-handler/#modifiers-population-algorithm

**Comment by rsolomakhin** [comment]
You're right. I missed that part. The spec is good as-is.
