### ISSUE TITLE
How to support communication with a payment app after initial PR API interaction?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#143]
Hi all,

At the recent Web Payments IG ftf meeting, we discussed digital receipts, and
there was some support (in the form of raised hands) for enabling a "post Payment
Request API" flow where the merchant sends a digital receipt (or other information)
to the payment app that was selected by the user for the transaction. (Note: This thread
is not about digital receipt formats; it's about the flow of information from payee back
to payer after PR API has completed.)

Two pieces of information seem to be necessary:

 * Transaction id
 * Payment app id

I believe that Payment Request API and Payment Handler API provide for the communication of a transaction id.

Regarding a payment app id, I have the following requirements in mind:

REQ 1) The information must not reveal the identity of the payment app to the payee.
REQ 2) The user agent must not be required to store information about "which payment app handled which transaction id."

I was wondering whether using hashes would make sense:

- Upon registration of a payment app, the user agent computes a hash that uniquely identifies the payment app. This payment app id should be robust in the face of payment app updates (and perhaps other changes to the user environment) and ideally would be a one-time hash so that the merchant cannot detect that the same payment app was used for multiple transactions. It is probably also appropriate to ensure that the user has granted permission to the user agent
to route receipts asynchronously to a payment app.
- The user agent returns the payment app id along with other payment response data to the merchant. 
- The merchant calls the (non-existent) Payment Receipt API and provides the payment app id and other relevant data.
- The user agent compares the id with the database of payment app ids and routes the data to the corresponding payment app. How the payment app responds is up to the payment app. For example, the payment app might notify the user that it has received a receipt. 
- A response message to the merchant indicates success or failure. (If the payment app is no longer registered, the user agent would send a failure message to the merchant.)

Another potential requirement might be:

REQ 3) The system must prevent the user agent from routing the receipt to any payment app that was not the payment app used for the original transaction. This includes the requirement that no other payment apps must be made aware of the existence of the receipt.

To accomplish this, the transaction id might be used to generate the payment app id.

Although there is not yet any Working Group chartered to work on a Payment Receipt API,
I would like for us to discuss the general question of how to enable interaction with a payment app
for payee-initiated activities after Payment Request API. 

I do not expect to address this issue prior to FPWD. We may not address this issue in V1 at all.

However, I am interested in hearing from people whether they think this is an interesting use case, and also thoughts on the three requirements I've drafted.

Ian

[1] https://www.w3.org/2017/03/22-wpay-minutes#item04

**Comment by mattsaxon** [comment]
Ian,

Can I be clear on what use cases this is solving for? Is it so the app knows about the status of payments that are async?

I'm interested in receipts, but I think other use cases may be more important, e.g. a receipt from a payment app to a merchant that a payment has been completed, so the merchant can dispatch goods or allow download of digital media immediately.

Regards,
Matt

**Comment by ianbjacobs** [comment]
@mattsaxon,

Regarding the use case, the one I have in mind is the merchant returning a receipt to the payment app. I am using the word receipt here to mean "the thing that the merchant often mails the consumer." I am not using the term to mean "a signal that payment has completed."

Ian

**Comment by mattsaxon** [comment]
@ianbjacobs, ok, so then the Payment App could contact the payer, perhaps via email/SMS or whatever method it has.

The payment app usually has some sort of out of band connectivity to the payment systems for this information, so what need does this interaction meet that is not already met by the ecosystem?

**Comment by adrianhopebailie** [comment]
+1 to @mattsaxon 

It seems strange to me to treat the payment app as some kind of entity. It is a proxy for a service provider. The merchant will send the "receipt" to the service provider who can push it to their app.

**Comment by ianbjacobs** [comment]
I'm not sure I agree.

Suppose I make a payment with Amex at Amazon. When I look at my Amex bill, it does not have all the details of the transaction. Amazon sends me that information by email. (I can also recover it later at amazon.com.) 

The proposal here is to replace email with an API that allows me to keep all of my receipts from lots of vendors in one app.

I would like to gauge interest in this (for WPIG discussion). 

Ian

**Comment by adrianhopebailie** [comment]
In this case Amex is playing two roles: the provider of the app and the payment service provider.

My suggestion is that the provider of the app will get the receipt from Amazon not "the app". The mechanism for getting that data to the app is outside our scope.

I think a "pull" model is preferable here, where the app/service provider pulls the receipt details from the merchant after the transaction using a URL that the merchant provides in the payment request.

**Comment by msporny** [comment]
> The merchant calls the (non-existent) Payment Receipt API and provides the payment app id and other relevant data.

-1, Digital Bazaar would object to a design where the browser routes receipts to payment apps for at least these reasons: 1) in a number of cases, you can't deliver the receipt immediately and it must therefore be done at a later time where the browser may not be available, and 2) this could potentially conflict with the way we could store digital receipts using a future Verifiable Claims API.

I suggest the WPWG coordinates with the Verifiable Claims WG on this as digital receipts are in scope for that charter.

We would prefer that an HTTP endpoint is provided in the PaymentResponse that can then be used by the merchant to push a receipt asynchronously (when it's ready). An endpoint that allows a receipt to be pulled, as @adrianhopebailie suggests, is also appropriate. We're less interested in the details at this point than we are the general design, which SHOULD NOT be browser centric.

**Comment by ianbjacobs** [comment]
Thanks, all. I'll take this feedback back to the Web Payments IG, which is discussing digital receipts.

I posted the issue in this forum to raise awareness on the *potential* need for post PR API payment app identification. This use case may or may not justify changes to the spec. But I wanted to have an anchor if we identify use cases that require payment app identification.

I will leave this issue open for now but am likely to close it after some additional WPIG discussion.

Ian

**Comment by ianbjacobs** [comment]
Hi all,

Right now there is no digital receipts champion in the WPIG and so I am going to close this issue here. If the need arises in the future for more identity regarding payment apps, I will reopen this.
