### ISSUE TITLE
Establish Editorial process

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-payment-apps-api#156]
After FPWD it's imperative we put in place an editorial process that mirrors the Payment Request spec. 

In particular: 

 * Commit message structure (chore:, editorial:, etc.)
 * no review from implementers, no merge. 
 * No merge commits!

Some of these things can be enforced by github.

**Comment by adrianhopebailie** [comment]
Sounds like you are volunteering to be an editor? 😄

**Comment by ianbjacobs** [comment]
I'm ok with that approach, and also with Marcos becoming an editor.

Ian

**Comment by marcoscaceres** [comment]
Yep, I'll definitely help edit.

**Comment by msporny** [comment]
> no review from implementers, no merge.

Editorial changes can still be done w/o implementer review, I assume?

Who is implementing?

Digital Bazaar has committed to do the polyfill implementation after FPWD (sometime during the summer, most likely).

**Comment by adrianhopebailie** [comment]
> Who is implementing?

@rsolomakhin can confirm but I think Google are implementing. I'm hopeful that Mozilla will too since they will soon have 2 editors on the spec and Opera (@tommythorsen) are also editors so I expect they plan to as well.

**Comment by rsolomakhin** [comment]
Google is implementing Payment Handler spec.

**Comment by marcoscaceres** [comment]
We (Moz) are going to investigate the feasibility of implementing over the next few months. There are similarities between this specification and foreign fetch, which is challenging for us (Mozilla) given some limitations in our current implementation of service workers. 

However, we remain optimistic that we will be able to implement and remain supportive of this work - and we intend to continue to work with the fine folks in this WG towards creating a great solution for the web to enable web apps to handle requests for payment.

**Comment by marcoscaceres** [comment]
Better: https://whatwg.org/working-mode

**Comment by ianbjacobs** [comment]
I am going to close this issue as we have a functioning editorial process; can reopen if needed.
