### ISSUE TITLE
Dead link in an example

### ISSUE THREAD

**Issue by tyoshino** [w3c/webpayments-payment-apps-api#166]
"EXAMPLE 3: Simple Payment Handler Window" has this link which is dead.
https://w3c.github.io/webpayments-payment-apps-api/#sec-app-response

**Comment by ianbjacobs** [comment]
Hi @tyoshino,

Where did you find that link? We renamed the repo so perhaps some old github.io links were not redirected.

I think the new URL would be:
 https://w3c.github.io/payment-handler/#response

Ian

**Comment by tyoshino** [comment]
I didn't mean that I cannot access it and want to read it. I meant that the example ("EXAMPLE 3: Simple Payment Handler Window") in https://w3c.github.io/payment-handler/ has "https://w3c.github.io/webpayments-payment-apps-api/#sec-app-response". It should be replaced.

**Comment by ianbjacobs** [comment]
Aha, now I see it. Thank you for the heads-up.

Ian

**Comment by ianbjacobs** [comment]
Pull request to address this:
 https://github.com/w3c/payment-handler/pull/172

**Comment by ianbjacobs** [comment]
Closed with merge of pull request #172
