### ISSUE TITLE
is PaymentRequestEvent.openWindow should check origin before navigation instead of after navigation

### ISSUE THREAD

**Issue by gogerald** [w3c/webpayments-payment-apps-api#168]
OpenWindow algorithm 8-4 checks origin after navigation, however from this bug discussion https://github.com/w3c/payment-handler/issues/163, it looks we would like to check origin before navigation.

**Comment by ianbjacobs** [comment]
@romandev, this seems related to https://github.com/w3c/payment-handler/issues/163
so please note this in any updates to the algorithm. Thanks!

Ian

**Comment by romandev** [comment]
IMHO, even if we add this check to the algorithm, we should keep the original check logic.
For example, the input origin was a proper origin, but if the origin is set as unexpected origin after navigation(e.g. redirection), then the SW might not controll the windowClient anymore.

**Comment by ianbjacobs** [comment]
Closed (I believe) through PR #171
