### ISSUE TITLE
PaymentRequestEvent.total

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#175]
The [`PaymentRequestEvent.total`](https://w3c.github.io/payment-handler/#dom-paymentrequestevent) is defined to have a type of [`PaymenItem`](https://w3c.github.io/browser-payment-api/#paymentitem-dictionary), which is a dictionary. However, [WebIDL spec](https://heycam.github.io/webidl/#idl-dictionaries) says that attributes should not be dictionaries.

**Comment by romandev** [comment]
I'm not sure but the spec says that:

> The type of the attribute, after resolving typedefs, must not be a nullable or non-nullable version of any of the following types:
> 
> - a sequence type
> - a dictionary type  <<-- Maybe.. possible?
> - a record type
> - a union type that has a nullable or non-nullable sequence type, dictionary, or record as one of its flattened member types

If I'm missing something, please correct me.

https://heycam.github.io/webidl/#idl-attributes

**Comment by rakuco** [comment]
> must not be a nullable or non-nullable version of any of the following types:
> * a dictionary type

Doesn't that corroborate @rsolomakhin's comment? That also matches https://heycam.github.io/webidl/#idl-dictionaries, which says _"Dictionaries must not be used as the type of an attribute or constant."_

**Comment by ianbjacobs** [comment]
Hi all,

Here's some guidance from a draft WebIDL cookbook [1]:

===
Use type any or object and describe in prose that the attribute takes the type of the dictionary.

Example 22
   interface HasRightUsage {
    readonly attribute any dict;
    };

 In your spec, write "dict is of type IAmDictionary dictionary as defined in [REFERENCE]". 
=====

Ian

[1] http://darobin.github.io/api-design-cookbook/#attribute-constant-or-exception-fields
