### ISSUE TITLE
PaymentRequestEvent.total should be PaymentCurrencyAmount.

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#179]
The spec says that `PaymentRequestEvent.total` is [`PaymentItem`](https://w3c.github.io/browser-payment-api/#paymentitem-dictionary), e.g.:

```javascript
{
  label: "Total",
  amount: {
    currency: "USD",
    value: "1.00",
    currencySystem: "urn:iso:std:iso:4217"
  },
  pending: false
}
```

I propose that `PaymentRequestEvent.total` should not include the `label` and the `pending` attributes, because these are useless for the payment app. Instead it should be [`PaymentCurrencyAmount`](https://w3c.github.io/browser-payment-api/#paymentcurrencyamount-dictionary), e.g.:

```javascript
{
  currency: "USD",
  value: "1.00",
  currencySystem: "urn:iso:std:iso:4217"
}
```

**Comment by rsolomakhin** [comment]
Thank you for the support. I will send out a PR.

**Comment by ianbjacobs** [comment]
Resolved to adopt
https://www.w3.org/2017/06/20-apps-minutes.html#item04
