### ISSUE TITLE
respondWith behavior not specified

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/webpayments-payment-apps-api#190]
Unless I'm missing something, I don't see anything in the spec that (formally or even informally) describes what the respondWith method is supposed to do? All I see is https://w3c.github.io/payment-handler/#respondwith()-method, but that doesn't actually have any described behavior, just what it is used for.

**Comment by mkruisselbrink** [comment]
https://w3c.github.io/payment-handler/#details-attribute seems to have some further text. Although it seems to have a MUST requirement to run an algorithm if the promise is rejected, but the algorithm is left completely up to implementers? That doesn't really make sense. It can't be a MUST requirement if there isn't any actually required behavior.

Ah, and I guess the next paragraph is describing the behavior if the promise is resolved. Maybe the respondWith description could be extended to actually link to the spec text describing its behavior? I'm also not sure how things like failures during the structured clone (or the supposed json-serializable requirements) are supposed to be dealt with by implementations. More formal algorithmic descriptions of the behavior of respondWith would be really helpful.

**Comment by ianbjacobs** [comment]
Closing this after merge of pull request #194.

Ian
