### ISSUE TITLE
The Open Window Algorithm tries to access [[state]] of a request in a way that doesn't make sense

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/webpayments-payment-apps-api#192]
In the Payment Request API spec the [[state]] of a request seems to be handled fairly consistently always from tasks posts to the user interaction task source (or directly from methods called by javascript). But now in this spec the Open Window algorithm is suppose to somehow synchronously inspect this [[state]] from a completely different event loop (the service worker, rather than the originating document)? I'm not sure how implementations are supposed to implement, or even how that is supposed to work.

**Comment by gogerald** [comment]
Thanks for creating this bug. 

It looks hard to completely prevent open window in this case. Merchant websites and users can initiate canceling payment request at any moment (event after OpenWindow is called). So we might could just remove this check and let AbortPaymentRequest notice payment handler to close opened window. Notice that we already have 8 and 11 in the OpenWindow algorithm to prevent open multiple windows multiple times.

**Comment by rsolomakhin** [comment]
I believe we can safely remove the [[state]] check without detrimental effects on the user. 

Consider:

- The openWindow() algorithm already requires a valid PaymentRequestEvent object, which is generated by the PaymentRequest when in "interactive" [[state]].
- During the handling of PaymentRequestEvent, the user should not be able to interact with PaymentRequest UI.
- When the service worker's window has been opened, the user should be able to interact only with the service worker's window.
- When the service worker's window closes itself, the service worker will finally call PaymentRequestEvent.updateWith(), which will move the PaymentRequest [[state]] from "interactive" to "closed" on success. On failure, PaymentRequest [[state]] will remain "interactive."
- If the merchant calls PaymentRequest.abort() at any point during this process, AbortPaymentEvent will be sent to the service worker, allowing it to gracefully close the window. If the service worker does not have a handler for AbortPaymentEvent, then PaymentRequest.abort() promise is rejected. The service worker's window stays open.

Therefore, there's no instance in time when the "interactive" [[state]] check is useful.

**Comment by rsolomakhin** [comment]
Pull request https://github.com/w3c/payment-handler/pull/196 removes the [[state]] check. Does it look OK? @mkruisselbrink @gogerald

**Comment by mkruisselbrink** [comment]
Sounds good to me. I haven't studied the spec in enough detail to be able to really say what the effect of (not) having the check is, but not having the check definitely seems better than having a racy check.

**Comment by gogerald** [comment]
It looks good to me,

**Comment by rsolomakhin** [comment]
Fixed via https://github.com/w3c/payment-handler/pull/196
