### ISSUE TITLE
`requestPermission` is static in Web IDL but example is not

### ISSUE THREAD

**Issue by dlongley** [w3c/webpayments-payment-apps-api#198]
While working on implementing a polyfill for the API I noticed that the [spec](https://www.w3.org/TR/payment-handler/#paymentmanager-interface) indicates that the `requestPermission` call on the `PaymentManager` interface is `static`. However, the [example](https://www.w3.org/TR/payment-handler/#register-example) calls it on the service worker registration's `paymentManager` instance (rather than directly on the class).

Should the example be fixed or the Web IDL?

**Comment by adrianhopebailie** [comment]
Resolved by https://github.com/w3c/payment-handler/pull/199
