### ISSUE TITLE
Registration example accesses `registration` before it is defined

### ISSUE THREAD

**Issue by dlongley** [w3c/webpayments-payment-apps-api#200]
In the [registration example](https://www.w3.org/TR/payment-handler/#register-example) the service worker `registration` variable is accessed before it is defined. I recommend moving the registration retrieval and `paymentManager` feature check to the top of the method:

```js
button.addEventListener("click", async() => {
  const { registration } =
    await navigator.serviceWorker.register('/sw.js');
  if (!registration.paymentManager) {
    return; // not supported, so bail out.
  }

  const permission =
    await navigator.permissions.query({ name: "paymenthandler" });
  switch (permission) {
    case "denied":
      return;
    case "prompt":
      const result = await registration.paymentManager.requestPermission();
      if (result !== "granted") {
        return;
      }
      break;
  }

  // Excellent, we got it! Let's now set up the user's cards.
  await addInstruments(registration);
}, { once: true });
```

**Comment by dlongley** [comment]
I suspect that this could be further simplified to just call `requestPermission` as well:

```js
button.addEventListener("click", async() => {
  const { registration } =
    await navigator.serviceWorker.register('/sw.js');
  if (!registration.paymentManager) {
    return; // not supported, so bail out.
  }

  const result = await registration.paymentManager.requestPermission();
  if (result !== "granted") {
    return;
  }

  // Excellent, we got it! Let's now set up the user's cards.
  await addInstruments(registration);
}, { once: true });
```

This presumes that a call to `requestPermission` would, in effect, initially do the same thing as a `query` on the permission manager to see if permission was already granted (and return early). Off the top of my head, I believe this is how `Notification.requestPermission` works but I could be rusty on that.

**Comment by dlongley** [comment]
Also, if we aren't going to simplify (for whatever reason) to just using `requestPermission`, then the return value from `navigator.permissions.query`, I believe, is actually a [PermissionStatus](https://w3c.github.io/permissions/#permissionstatus), which would mean we should be checking its `state` attribute, whereas `requestPermission` returns the `PermissionState` directly:

```js
button.addEventListener("click", async() => {
  const { registration } =
    await navigator.serviceWorker.register('/sw.js');
  if (!registration.paymentManager) {
    return; // not supported, so bail out.
  }

  const permission =
    await navigator.permissions.query({ name: "paymenthandler" });
  switch (permission.state) {
    case "denied":
      return;
    case "prompt":
      const result = await registration.paymentManager.requestPermission();
      if (result !== "granted") {
        return;
      }
      break;
  }

  // Excellent, we got it! Let's now set up the user's cards.
  await addInstruments(registration);
}, { once: true });
```

**Comment by dlongley** [comment]
So I promptly forgot that `registration.paymentManager.requestPermission` has been fixed to use the static method on `PaymentManager` (#198). I should have been looking at the latest draft. So all that should be looked at here is either a fix to use the `state` attribute after the permission query or the possible simplification to just use `PaymentManager.requestPermission`:

```js
button.addEventListener("click", async() => {
  if (!window.PaymentManager) {
    return; // not supported, so bail out.
  }

  const result = await PaymentManager.requestPermission();
  if (result !== "granted") {
    return;
  }

  const { registration } = await navigator.serviceWorker.register('/sw.js');

  // Excellent, we got it! Let's now set up the user's cards.
  await addInstruments(registration);
}, { once: true });
```

**Comment by ianbjacobs** [comment]
Hi @dlongley,

Would you mind submitting a pull request for this? Thanks!

Ian
