### ISSUE TITLE
Stop committing things without tests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-payment-apps-api#205]
Please stop committing things into this repo without tests. 

It puts an extremely unfair burden on others to then verify everything in the spec afterwards. 

I'll will be blocking all pull requests that come in that don't have tests.

**Comment by adrianhopebailie** [comment]
@marcoscaceres this spec is currently a **working draft** that reflects the fast evolving single implementation we have. 

It is not under the same process burden as the more mature specs that are progressing to CR.

When the spec and implementation have stabilized we will turn our attention to writing tests.
