### ISSUE TITLE
Clarification of "instrumentKey" language

### ISSUE THREAD

**Issue by madmath** [w3c/webpayments-payment-apps-api#212]
It is my understanding that "instrumentKey" is not going to be set equally by all implementers as part of the "paymentrequest" event. 

self.addEventListener('paymentrequest', function(e) {
  // e.instrumentKey may or may not be set.
});

The [current draft text](https://w3c.github.io/payment-handler/#paymentinstruments-interface) says: 

> The instrumentKey identifier will be passed to the payment handler to indicate the PaymentInstrument selected by the user, if any.

I can see how "if any" may indicate that instrumentKey may not be set, but I would recommend language such as "the instrumentKey identifier may be passed if a specific PaymentInstrument has been selected by the user".

cc @rsolomakhin

**Comment by rsolomakhin** [comment]
Resolved in a [pull request](https://github.com/w3c/payment-handler/commit/dcf3f360e2f8d9f917aaba36b5bfb0a72556eedd). Empty string means that user has not selected an instrument.
