### ISSUE TITLE
Return origin of payment app in PaymentHandlerResponse data?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#217]
I am raising this issue on behalf of @adrianhopebailie who mentioned this topic
came up in a conversation about Payment Request API and Payment Handler.

Ian

**Comment by rsolomakhin** [comment]
What use case are you trying to address?

**Comment by ianbjacobs** [comment]
I believe the idea is that some merchants may not want to accept a payment response from some payment apps. I will let @adrianhopebailie expand.

Related to this is whether merchants should be able to specify as input data for open payment methods the list of origins of payment apps they accept.

Ian

**Comment by rsolomakhin** [comment]
Rejecting a payment after user has approved the transaction is bad UX. If a merchant does not trust 50% of merchants using https://some-payment-method.com, then the merchant should not be using that payment method, IMHO. That allows the browser to pre filter out unacceptable choices before the user sees the browser selection UI.

**Comment by adrianhopebailie** [comment]
> Rejecting a payment after user has approved the transaction is bad UX.

Agreed. This has come up as a requirement. Let's discuss here and if we decide it can't be done without compromising the design then we can close the issue as wontfix.

**Comment by ianbjacobs** [comment]
Today if a merchant wants to use PR API and control the list of payment apps that appear to the user, they can mint their own payment method identifier. However, if we want to enable merchants greater control over which payment apps the user can use, that seems like the wrong approach. 

Another approach would be for the merchant to declare payment app origins they accept, and to use those (payment method manifest style) to filter out some payment apps from other origins.

This has privacy implications - the merchant can infer what the user does not have.

Ian

**Comment by ianbjacobs** [comment]
See comments on this thread from Laura Townsend:
 https://lists.w3.org/Archives/Public/public-payments-wg/2017Oct/0007.html

**Comment by marcoscaceres** [comment]
The merchant is effectively in control of which payment apps it supports - so it can only be an “origin” from those PMIs the merchant lists (thus there is a mitigated risk). The modifiers already allow for custom offers to be made, without needing to further  compromise user privacy. And the methodName in the response tells the merchant which “origin” (via the PMI) handled the request. 

I’m wondering if the above addresses everything?

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

The merchant controls the payment methods it accepts. For open payment methods, it does not directly control the payment apps that the user will use. The payment method identifier is not, for open payment methods, sufficient to identify the user's selected payment app.

The question is whether (for Web-based payment apps) to return the origin of the payment app selected.

Ian

**Comment by marcoscaceres** [comment]
I don’t know what an “open payment method” is? Do you mean “basic-card” and friends? If so, then it’s true that those won’t have an origin (native apps don’t have origins, for instance). Also, the browser’s payment sheet won’t have an origin. 

AFAIK, it’s still not clear if a website can register itself as capable of handling “basic-card” - or has that changed?

**Comment by ianbjacobs** [comment]
@marcoscaceres 

Yes, basic card and others that the WG is working on. There is currently an expectation that Web sites will be able to register to support any of those payment methods.

Ian

**Comment by marcoscaceres** [comment]
what if they could register themselves as both (url-based pmi and standardized pmi)? That would allow for promotions, and return the origin on match... and also preserve privacy.

**Comment by ianbjacobs** [comment]
@marcoscaceres,

If I understand the proposal correctly you are suggesting that every time someone wants to publish a payment app, they would publish a payment method identifier to go with it.

While nothing prevents that, it seem like an unnecessary burden to require a payment
app distributor to publish a payment method URL to go with it, and to require merchants
to update their sites to accept those apps.

Ian

**Comment by marcoscaceres** [comment]
I don't understand how adding a short string is a burden, particularly if it addresses the use cases while being privacy preserving?

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

I am confused. Perhaps we should take this up by phone to clarify.

Ian

**Comment by marcoscaceres** [comment]
Let's be clear on what is being asked: 

>  Merchants would like this type of “origin” information to enable the ability to manage their risk (ie. Payment types that have a significantly higher fraud chargeback rate), identify and address poor performance that don’t meet SLA’s

Unless a merchant is banning an origin outright, knowing the origin doesn't buy one much (particularly if it's a mix of fraudulent and legit payment responses). The merchant still needs to validate the `details` of each response in case they are legitimate. 

As I stated earlier, there are caveats here:
 
 1. The browser's payment sheet won't have an origin.
 1. Browser extensions serving as payment handlers won't have an origin.
 1. Native applications serving as basic card, etc. won't have an origin. 

Now, the case can be made that knowing that `evil.com` keeps sending fraudulent credit cards or tokens - but the tradeoff is exposing what site is serving as the user's wallet (i.e., privacy). 

I'm not entirely convinced yet that this would be an issue on any significant scale, but would be interested in playing out this scenario. 

The preconditions would be:

 1. A lot of users have somehow ended up at `evil.com` and allowed `evil.com` to serve as basic card. Or, `bank.com`'s service worker has been hacked, making it respond with bad tokens or credit cards.
 1. The affected people then end up at `merchant.com` and still opt to pay with `evil.com` (or think that `bank.com` is not compromised). 
 1. ??? 

> and enable partnership opportunities for promotions, offers, or discounting based on payment type or “origin”.  
>

This is addressed by URL-based PMI + `modifiers` + `methodName`. Would you agree? 

It's literally what we show in [this example](https://www.w3.org/TR/payment-request/#conditional-modifications-to-payment-request).

You can't add "promotions, offers, or discounting" _after_ you get the payment response, only before. So getting the origin _after_ doesn't help with any of the above.  

> These are just a few use cases for which an “origin” could support – all of which are to enhance the customer experience (with the exception of bad issuer behaviors or customer behaviors around fraud … which should be addressed with a balance of customer experience and risk management). 

So, that only really leaves "we don't know who is spamming us with fake card data and tokens, but we'd like that to stop!" as the only reasonable ask... but again, that needs to be balanced with user's privacy wrt what wallet (origin) they are using.

**Comment by marcoscaceres** [comment]
Fixed some typos above.

**Comment by rsolomakhin** [comment]
IMHO, if a merchant has requirement about origins of payment apps, they should use URL-based payment method names (e.g., https://bobpay.xyz) instead of standardized payment methods names (e.g., basic-card).

**Comment by ianbjacobs** [comment]
Hi all,

I am at a conference today where one person commented that when a problem occurs in a transaction that involved a payment handler, it's important for debugging purposes to know which payment handler was used. I wanted to add that as another use case for returning the origin of the payment handler in the response data.

**Comment by rsolomakhin** [comment]
I'm starting to warm up to this idea. Wondering what should be returned when a built-in or 3rd party Android payment app was used...

**Comment by ianbjacobs** [comment]
@rsolomakhin, one idea is to have an enumeration in conjunction with an identifier:
    handlerType: {built-in, web, native)
    handlerID: {none, &lt;origin&gt;, &lt;platform-specific&gt; }

Thoughts?

**Comment by rsolomakhin** [comment]
That could work.

**Comment by ianbjacobs** [comment]
@rsolomakhin, sorry I used angle brackets which were lost...I meant to say for web-based you would get back an origin (or handler scope) and for native you'd get back something platform-specific.

**Comment by ianbjacobs** [comment]
@rsolomakhin, the proposal to identify the type of payment handler makes sense if the data is part of a response from PR API. However, if the data is part of the PH API, then we only need to account for Web-based payment handlers (hence, origin).

**Comment by rsolomakhin** [comment]
@ianbjacobs, the data from PH API is set by the PH. We would not want a malicious PH to lie about its origin. The origin information should come from the browser, so it should be a part of the PR API, IMHO.

**Comment by ianbjacobs** [comment]
@rsolomakhin, I can see the case of making this part of PR API (to handle non-web payment handlers as well). But even if we were to only do this for Web-based payment handlers, this could be part of how the browser implements PH API - the response data (origin) is computed by the browser, not the payment handler itself. I agree with you on that point. But that could just be part of conformance to PH API.

**Comment by adrianhopebailie** [comment]
> I can see the case of making this part of PR API (to handle non-web payment handlers as well).

+1

We could add this to PR API today and return something like `user-agent` (or an appropriate URI) if the response is returned by the browser.

I suspect this is useful information for the auth flow too (e.g. 3DS)

**Comment by ianbjacobs** [comment]
Moving to PR API issues list and closing here:
 https://github.com/w3c/payment-request/issues/815
