### ISSUE TITLE
User consent and permissions

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#239]
We at Chrome would like to experiment with prompting user for consent to install a payment handler at the time of payment. This would imply the following behavior:

 1. Any service worker can set up its own instruments in the payment manager silently.
 2. When `paymentRequest.show()` is called, the user will have the opportunity to allow or deny the available payment handlers and also potentially block offending origins from installing a payment handler ever again.

This implies that `PaymentManager.requestPermission()` call in Chrome would always return `"allow"`. Do other implementers plan to make use of `requestPermission()`? If so, let's leave it in the spec. Otherwise, we would be OK removing this call entirely. Soliciting feedback from @romandev and @marcoscaceres in particular. 

cc: @anthonyvd @gogerald

**Comment by ianbjacobs** [comment]
@rsolomakhin,

What is the service worker able to do (silently, before consent) other than register instruments?
Ian

**Comment by rsolomakhin** [comment]
Nothing else, @ianbjacobs. The service worker will not receive any payment events until user consent. That includes `canmakepayment`, `paymentrequest`, and `abortpayment`.

**Comment by romandev** [comment]
> When paymentRequest.show() is called, the user will have the opportunity to allow or deny the available payment handlers and also potentially block offending origins from installing a payment handler ever again.

I think it's a good idea, but there seems to be a little risky points.

So I have some questions.
When paymentRequest.show() is called, all registered payment apps are shown on payment sheet?
What happens if some fishing site installs a large number of fishing payment apps for malicious purpose? Are they also shown on the payment sheet before asking a permission?

For example,
- I ususally use `Hello Pay` (https://hellopay.com).
- When surf on the internet, fishing apps are installed involuntarily.
- The fishing apps has the same look-and-feel with `Hello Pay`.
- Moreover the fishing apps is not one. (too much)
- So, it's difficult to select payment app because the app list is too long.
- Even if the origin is shown, but the fishing apps also might have similar origins such as https://hellopay.co, https://hellopay.net, and so on.

**Comment by rsolomakhin** [comment]
Hi @romandev,

Thank you for bringing up these concerns. We should document these concerns and the possible mitigations in the spec for the benefit of all implementers and web developers. Here's what I'm thinking:

1. Browsers should allow installing payment handlers only from top-level context or an iframe with appropriate permissions, (e.g., `allowpaymentrequest` can be reused here). Thus, to install a payment handler from https://hellopay.co, you would need to first visit that website or some other website that trusts http://hellopay.co.

2. Browsers should use [payment method manifests](https://w3c.github.io/payment-method-manifest/) to verify that https://alicepay.xyz is allowed to handle payments for https://bobpay.xyz payment method. Thus, to see a payment handler from https://alicepay.xyz when attempting payment via https://bobpay.xyz/pay payment method, the owners of https://bobpay.xyz/pay would first have to grant permissions to https://alicepay.xyz to use their payment method name.

3. Before user consent, browsers should show only the origin of the payment handler. Thus, even if https://hellopay.co uses the same name and icon as https://hellopay.com, the user will not see those before giving consent. After user clicks [ allow ], the browser would show the name and icon for the payment handler and the user should have the opportunity to check those against their expectations and potentially block a misbehaving payment handler by origin.

Let me know whether I've addressed your concerns sufficiently. We plan to implement all three of these mitigations in Chrome. 

Cheers,
Rouslan

**Comment by rsolomakhin** [comment]
cc: @DurgaTheHutt

**Comment by adrianhopebailie** [comment]
I think there us a still a use case for an a publisher of a handler to get the user consent out of the way before the payment flow.

i.e. I login to my bank's online banking and they prompt me to install their payment handler so that I can use it to pay "more securely" when shopping online. I click the "install" button and the SW is registered.

As the bank I'd want to user to give consent to the handler handling payment requests during that flow.

**Comment by rsolomakhin** [comment]
Good point, @adrianhopebailie. In Chrome, I would like to show an icon in the address bar to indicate when a payment handler is being installed. If the user taps on the icon, they will have an opportunity to allow or deny the installation at that time (as well as during payment). If the user does not tap on the icon, then it's out of the way and does not annoy the user. This is similar to the [diamond icon in gmail](https://img.gadgethacks.com/img/70/04/63540940943228/0/search-gmail-compose-new-emails-straight-from-chromes-address-bar.w1456.jpg) tab that can set it as the default e-mail handler. A webpage can direct the user to act upon that icon as well. Do you think this would be sufficient for your use case?

**Comment by adrianhopebailie** [comment]
> Do you think this would be sufficient for your use case?

I think it's a good start. Let's get some experience with this and see where it takes us.

**Comment by rsolomakhin** [comment]
Interesting point from @mhahmadi: If the payment button is in an `<iframe allowpaymentrequest src="...">` provided by the payment app website, this `<iframe>` can install the payment handler as well, which would be a nice bootstrapping mechanism for that particular use case.

**Comment by ianbjacobs** [comment]
Noting here we discussed today on the editors' call:
https://www.w3.org/2017/12/04-apps-minutes.html#item02

**Comment by rsolomakhin** [comment]
Here's a summary of the discussion at the editor's call this morning:

* The spec should note that user consent is required before first usage of the payment handler.
* The payment handler website may want to know whether the user granted the permission. This can happen after saving the payment instruments. Therefore, it may be more clear to rename `.requestPermission()` into `.requestPermissionState()`. That call can tell the payment handler website the state of the user consent (allow, deny, not decided yet) without blocking the setup of payment instruments.
* The user can grant permission at either (1) time of registration on payment handler website, (2) time of payment in payment sheet, or (3) any time after registration in browser settings.
* If a user logs into their bank from a public computer, then logs out, the next user may see a preview of the previous user's payment handlers, e.g., "Bank Inc (Visa****1234) [ icon ]" in the payment sheet, although they will not be able to see the full instrument or use it for payment. How can we prevent this?

**Comment by ianbjacobs** [comment]
@rsolomakhin,

When we have spoken previously about public usage, several comments have been made:

 1. The user needs to be able to clear data manually; we are talking about this in issue 236.
 2. The user needs to be able to explicitly say "Don't save this payment data for future use" when
    entering data [into the sheet]. 
 3. The owner of the public computer should also be able to configure the browser 
    so that payment data is not stored (whether the user checks a box or not).

We should think about each of those cases explicitly.

Some notes:

 * If the user logs out of bobpay.com, clear all the instrument data from bobpay.com.
 * Clear instrument data after show() or abort(). Or prompt the user to see whether
   they want to keep data for subsequent transactions.

Going to my next call...more later :)

Ian

**Comment by dlongley** [comment]
@rsolomakhin,

> The payment handler website may want to know whether the user granted the permission. ... Therefore, it may be more clear to rename .requestPermission() into .requestPermissionState(). 

Note that this query can already be done with [`navigator.permissions.query`](https://w3c.github.io/permissions/#dom-permissions-query), but the name of the permission will need to be passed.

For example:

```js
const result = await navigator.permissions.query({name: 'paymenthandler'});

// result.state is `granted`, `denied`, `prompt`
```

More examples here:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions

Using `requestPermission` mirrored the Notifications API, but I think `requestPermissionState` would be a new invention? I'm not sure if we need it in that case.

**Comment by rsolomakhin** [comment]
@dlongley: Thank you for the clarification! That's excellent.

**Comment by rsolomakhin** [comment]
Does [just-in-time install](https://github.com/w3c/payment-handler/issues/240) take care of this use-case? Need to double-check, but we may be able to close this issue and leave the spec as-is.

**Comment by rsolomakhin** [comment]
> Experiment with prompting user for consent to install a payment handler at the time of payment.

Double-checked with the team. That's not something that we plan to do. Closing this up!
