### ISSUE TITLE
Require secure contexts for web-based payment apps

### ISSUE THREAD

**Issue by adamroach** [w3c/webpayments-payment-apps-api#24]
This is a recommendation from the Security and Privacy Checklist review. See https://docs.google.com/document/d/1w7ginyzNg-xZUmITK4vzcGUKB4gbMOAvlkWWaRtX14k/edit?usp=sharing for additional detail

Although the payment apps specification has not yet been taken up by the Working Group, we also expect that it will require payment apps to run in secure contexts. Information can be transferred between these two contexts using the Payment Request API, but such transfer will be between secure contexts, and (we presume) policed by the user agent.

**Comment by ianbjacobs** [comment]
Hi @adamroach,

My sense is that if your proposal is adopted, it will involve language about invoking the payment app in a secure context. Is that your expectation?

Ian

[1] https://github.com/w3c/webpayments-payment-apps-api/blob/gh-pages/proposals/jsapi.md

**Comment by adamroach** [comment]
Yes, I would expect that the edits that put my proposal into the document would also include a note about executing in a secure context.

**Comment by ianbjacobs** [comment]
Here is the sort of language that will be in the payment apps spec:

 "If the current settings object is not a secure context, reject promise with a DOMException whose name is "SecurityError" and terminate these steps. "

I am going to close this issue in anticipation of the inclusion of that language in an upcoming draft.
