### ISSUE TITLE
Does payment instrument registration imply a display order?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#243]
This topic came up based on a post by @msporny:
 https://github.com/w3c/payment-handler/pull/242#issuecomment-351599849

If payment instruments are displayed by the user agent (e.g., for fast access to individual instruments), is that display order specified through registration or another mechanism (e.g., browser heuristics).

Ian

**Comment by dezell** [comment]
First, apologies for being late to post here, and having not stayed close to the discussion.

Based on Conexxus understanding of the regulatory environment and experience with the ISO12812 specification, there are implications for choice in ordering:
1) customers MUST be able to control the order - consumer choice is a first priority in most regions
2) merchants SHOULD have some control over the order (ability to “steer” the flow) - there may be legal requirements in some regions
3) lack of control by customer or merchants implies the browser controls the order.  This situation may bring unwanted scrutiny by regulators in some regions

Summary:
* failure to provide for 1 and 2 should be avoided
* 3 could potentially make a browser non-compliant

**Comment by ianbjacobs** [comment]
Hi @dezell,

Do you have a position on whether payment handler API registration should define a payment instrument order (if displayed to the user for selection)?

Ian

**Comment by rsolomakhin** [comment]
In Chrome we are currently implementing display of payment apps only. Showing instruments is lower priority for us. Once we get the basic implementation shipped, we may experiment with showing instruments on desktop, where there's more room for it. When that happens, I would prefer to use [frecency](https://en.wikipedia.org/wiki/Frecency) to sort instruments by default and also let the user manually set the order in settings. I don't believe the spec should contain this information, however.

**Comment by adrianhopebailie** [comment]
Note there is no way for merchants to infer order as this would need to be catered for in PR API (not here) so trying to accommodate this is moot.

I am comfortable saying nothing about display order OR saying it should be defined by the payment handler.

How the payment handler determines this order (user preference or other) is outside of our scope

**Comment by ianbjacobs** [comment]
Hi @adrianhopebailie and @rsolomakhin,

What about something like the following (which is close to what we have for payment apps)?

======
When the user agent displays multiple instruments for selection by the user:
 * User agents are expected to permit manual configuration options, such as as setting a 
    preferred instrument display order for a site, or for all sites.
 * User experience details are left to implementers.
======

**Comment by adrianhopebailie** [comment]
This is not as simple as that IMO. We are assuming that if instruments are shown they will be grouped by payment handler (which is not a requirement).

What if a browser wants to honour the user's preferences which are defined by payment method and there are two apps with instruments supporting the user's favourite payment method? Can the browser show these two first or must it first order the payment handlers (and if so, on what basis) and then the instruments.

At the most I think we can say that order of priority for the instruments from a single payment handler is inferred b y the order they are registered by the handler but beyond that, how that order is mixed in with other preferences, is UX space and not in scope for us.

**Comment by ianbjacobs** [comment]
In discussion at the 18 December PH API editors' call, there was agreement to add instruments along with handlers.
https://www.w3.org/2017/12/18-apps-minutes.html#item04

I have updated pull request #242 

Ian

**Comment by ianbjacobs** [comment]
Closed with merge of PR #242
