### ISSUE TITLE
Communication between JS PaymentApps and the User Agent

### ISSUE THREAD

**Issue by tommythorsen** [w3c/webpayments-payment-apps-api#26]
I've read through @adamroach's new [proposal](https://github.com/w3c/webpayments-payment-apps-api/blob/gh-pages/proposals/jsapi.md), which I think looks very promising. Making it a Worker definitely feels like the right approach to me.

According to the proposal, communication with the user agent is done through a `MessageChannel`. This is slightly different from how communication with the user agent is done in other workers (see [here](https://www.w3.org/TR/workers/#communicating-with-a-dedicated-worker) or [here](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-03?hl=en#add-event-listeners-to-your-service-worker)), which typically use `addEventListener` to set up communication.

Is there an advantage to using `MessageChannel` with `port1` for receiving messages and `port2` for passing messages back to the user agent? If there is no clear advantage, should we try to align this with the way serviceworkers and other workers are implemented?

**Comment by adamroach** [comment]
> Is there an advantage to using `MessageChannel` with `port1` for receiving messages and `port2` for passing messages back to the user agent? If there is no clear advantage, should we try to align this with the way serviceworkers and other workers are implemented?

I'm okay making the ports implicit by adding [global scope interfaces similar to Dedicated Web Workers](https://www.w3.org/TR/workers/#dedicated-workers-and-the-dedicatedworkerglobalscope-interface). Note that this will only impact the payment apps themselves; the actual posting of messages to the apps and receiving messages from the apps will be done by the payment mediator, not the payment requester.

**Comment by adamroach** [comment]
Okay, I have a new version of [the proposal](https://github.com/w3c/webpayments-payment-apps-api/blob/gh-pages/proposals/jsapi.md) up, based on Tommy's suggestion.

**Comment by tommythorsen** [comment]
Nice! I like the new version.
