### ISSUE TITLE
Found some typos in the wiki

### ISSUE THREAD

**Issue by mattijsbliek** [w3c/webpayments-payment-apps-api#284]
Unfortunately I could not make a PR for this, but I found two typos in the wiki:

"I only credit cards" -> "I only accept credit cards" [found here](https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice#capability-matching-beyond-payment-method-identifier-matching)

In the code block underneath [Payee identity](https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice#payee-identity) the leading `[` is missing from the data array.

**Comment by ianbjacobs** [comment]
Thanks @mattijsbliek for the review. I've made changes based on your comments; let me know if I addressed them. I also welcome more suggestions!

Ian

**Comment by mattijsbliek** [comment]
Perfect, thank you! I will be looking into what it would take to implement the Payment Request API and iDEAL #251 from a payment gateway perspective. If I have any other suggestions I’ll be sure to let you know.
