### ISSUE TITLE
HEAD request for supportedMethods not getting triggered

### ISSUE THREAD

**Issue by kishoretulsiani** [w3c/webpayments-payment-apps-api#286]
here is my sample code, this is part of majaybabu thread that showed that it is working on local.

but when we shifted to remote server we fail on the canMakePayment(), it is alway coming as false.

`function buildPaymentRequest() {

    const supportedInstruments = [
        {
            supportedMethods: 'https://abc-dev.test.com/pay3',
            data: {
                threeDS: true
            },
        }
    ];

    const options = {requestShipping: true};

    const details = {
        total: {
            label: 'Donation',
            amount: {
                currency: 'USD',
                value: '55.00',
            },
        },
        displayItems: [{
            label: 'Original donation amount',
            amount: {
                currency: 'USD',
                value: '65.00',
            },
        }, {
            label: 'Friends and family discount',
            amount: {
                currency: 'USD',
                value: '-10.00',
            },
        }],
    };

    var request = new PaymentRequest(supportedInstruments, details, options);

    if (request.canMakePayment) {
        request.canMakePayment().then(result => {
            if (result) {
                console.log('Payment methods are available.')
            } else {
                console.log('Payment methods are not available, but users can still add')
            }
        }).catch(error => {
            console.log('Unable to determine.')
        });
    }

    request.addEventListener('shippingaddresschange', function (evt) {
        evt.updateWith(new Promise(function (resolve) {
            updateDetails(details, request.shippingAddress, resolve);
        }));
    });

    return request;
}`

Want to understand at what line i should expect the HEAD request getting triggered?

because when we trigger "https://abc-dev.test.com/pay3" manually from client i am getting some logs on server, but this code is not triggering HEAD request at all.

**Comment by rsolomakhin** [comment]
If you have a payment handler installed that is not from `https://abc-dev.test.com` origin, but claims to support for `https://abc-dev.test.com/pay3`, then this line will trigger the HEAD request for `https://abc-dev.test.com/pay3`:

> `var request = new PaymentRequest(supportedInstruments, details, options);`

The HEAD request will be used to verify that the payment handler is indeed allowed to use this payment method. Note that, if the payment handler comes from `https://abc-dev.test.com` origin, then there's nothing else to verify, so there will not be any HEAD requests.

Here's how a payment handler would claim to support `https://abc-dev.test.com/pay3`:

```javascript
await navigator.serviceWorker.register('payment-handler-service-worker.js');
const registration = await navigator.serviceWorker.ready;
// The payment handler claims to support 'https://abc-dev.test.com/pay3'
// payment method in the following statement.
await registration.paymentManager.instruments.set(
    'instrument-key', {
        name: 'Chrome uses name and icon from the web app manifest',
        enabledMethods: ['https://abc-dev.test.com/pay3'], // Legacy.
        method: 'https://abc-dev.test.com/pay3', // Modern.
    });
```

**Comment by majaybabu** [comment]
Do we need both these lines during registration - mentioning the payment method twice.
enabledMethods: ['https://abc-dev.test.com/pay3'], // Legacy.
method: 'https://abc-dev.test.com/pay3', // Modern.

canMakePayments() is returning false where as we are able to see the Payment Handler on Payment popup screen.  What may be the reason here.

**Comment by rsolomakhin** [comment]
> Do we need both these lines during registration - mentioning the payment method twice.

You may want it for now for testing, especially if you're using Chrome Dev or Beta instead of Canary. Only the 'Modern' line is necessary going forward, however.

> canMakePayments() is returning false where as we are able to see the Payment Handler on Payment popup screen. What may be the reason here.

Perhaps you're hitting the just-in-time install flow. You don't have the payment handler installed, but https://abc-dev.test.com/pay3 points to an installable payment handler, so Chrome displays it as an option for the user to install.

**Comment by majaybabu** [comment]
We have the below install() function for registration.  These 2 console statements never get printed even after the SW is installed and activated. Is the SW not able to add the payment method ?

console.log('registration.scope is' + registration.scope);
console.log('enabledMethods is' +  instrument.method);

`function install() {
    console.log('installing');

    navigator.serviceWorker.register('/secure/sw.js').then(() => {
            return navigator.serviceWorker.ready;
        }).then((registration) => {
            if (!registration.paymentManager) {
                console.log('No payment handler capability in this browser. Is chrome://flags/#service-worker-payment-apps enabled?');
                return;
            }
            if (!registration.paymentManager.instruments) {
                console.log('Payment handler is not fully implemented. Cannot set the instruments.');
                return;
            }
            registration.paymentManager.instruments
                .set('instrument-key', {
                    name: 'Chrome uses name and icon from the web app manifest',
                    enabledMethods: ['https://americanexpress-dev.aexp.com/pay3'],
                    method: 'https://americanexpress-dev.aexp.com/pay3',
                })
                .then(() => {
                    registration.paymentManager.instruments.get('instrument-key').then((instrument) => {
                        console.log('registration.scope is' + registration.scope);
                        console.log('enabledMethods is' + instrument.enabledMethods || instrument.method);
                        console.log('installed');
                    }).catch((error) => {
                        console.log('error is' + error);
                    });
                })
                .catch((error) => {
                    console.log('error is' + error);
                });
        })
        .catch((error) => {
            console.log('error is' + error);
        });
}`

**Comment by majaybabu** [comment]
We are on Version 67.0.3393.4 (Official Build) dev (64-bit)

**Comment by majaybabu** [comment]
navigator.serviceWorker.ready was not resolving after SW activation. We moved the sw.js to the root folder and changed the registration line like this -

navigator.serviceWorker.register('sw.js').then(() => {

Now we are able to resolve navigator.serviceWorker.ready and registration is now successful.

**Comment by rsolomakhin** [comment]
Sounds like you've resolved all your issues so far, @majaybabu. Is that correct?

**Comment by majaybabu** [comment]
yes thats correct. Thanks @rsolomakhin for all your support on this.

**Comment by ianbjacobs** [comment]
In our Payment Method Good Practice documentation, I have added a more explicit mention of the payment method manifest (fetch algo):
 https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice#canmakepaymentevent-implementation

Thanks all!
