### ISSUE TITLE
Remove modifiers from CanMakePaymentEvent?

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#289]
I can't think of a use case where a modifier would be useful in the `CanMakePaymentEvent`. Modifiers also currently contain the total amount, which we do not want to provide before `PaymentRequestEvent`. Would it be OK with everyone if `CanMakePaymentEvent` did not include modifiers?

**Comment by ianbjacobs** [comment]
@rsolomakhin, don't we potentially need the additional "data"?

**Comment by rsolomakhin** [comment]
@ianbjacobs: Good question. We use the additional `data` to match the modifiers against payment instruments/handlers and display custom totals and custom display items for the matches. So the algorithm for processing modifiers would take `data` in, and spit `total` out. Since `total` should not be in `CanMakePaymentEvent`, the modifiers appear to be useless.

**Comment by ianbjacobs** [comment]
Having clarified that the payment method capabilities are available through the methodData member of canMakePayment(), I am ok dropping modifiers.

**Comment by ianbjacobs** [comment]
See nearby discussion on transaction id:
 https://github.com/w3c/payment-request/issues/760
