### ISSUE TITLE
Popup messages

### ISSUE THREAD

**Issue by majaybabu** [w3c/webpayments-payment-apps-api#297]
Hi , 

Is there a way to change or remove the domain name of the Payment Handler when the popup is shown  ?

**Comment by majaybabu** [comment]
@rsolomakhin  - Do you know if it is possible to not show the Payment Handlers domain name like 'https://bobay.xyz' on Payment popup screen ?

**Comment by romandev** [comment]
I'm not Rouslan but there is no way to hide the origin url in Chrome implementation for security reason. Could you explain why you want to remove it?

**Comment by majaybabu** [comment]
@romandev - Can you please elaborate the security reason to explicitly display the origin url

**Comment by ianbjacobs** [comment]
One reason is so that one knows to whom one is giving credentials. I think the idea is to reduce phishing attacks.

Ian

**Comment by ianbjacobs** [comment]
I am closing this as it is specific to one implementation.
