### ISSUE TITLE
Drop PaymentInstrument in favor of MethodCapability

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#302]
This was discussed at the 20 April Payment Handler breakout in Singapore. The suggestion was:

 * Because no browsers are currently planning to show instrument-level information, and
 * Because "instrument" suggests an instance of a payment method (e.g., an actual card) the name of the method+capability structure should be different.

@anthonyvd mentioned something like this:

<pre>
await  registration.paymentManager.setMethodCapabilities([
  {
    method: "basic-card",
    capabilities: {
     supportedNetworks: ['visa'],
     supportedTypes: ['credit']
     }
 },
 {
    method: "https://bobpay.com/"
 }
]);
</pre>

The method/capability pair could be called, for example, MethodCapability. Similarly, change
PaymentInstruments to MethodCapabilities.

Note that since the current expectation is that payment handlers will do the capability matching (via the CanMakePaymentEvent) in the case of URL-based payment methods, there is no need to register capabilities for bobpay.

**Comment by dlongley** [comment]
As mentioned previously, I'm in support of changing the name from `PaymentInstrument` to better reflect that what is being registered is actually some kind of user-selectable hint (plus some constraints by which the browser can filter) that the user and PaymentHandler mutually understand.

In my view, it has never necessarily represented a "payment instrument", rather there's some contract between the user and the PaymentHandler regarding what the specific meaning of the hint will entail. The only requirement, as far as the mediator (browser) is concerned, is that the hint include the aforementioned constraints so that matching can occur. So the name should reflect this concept.

**Comment by dlongley** [comment]
I'm not convinced that "MethodCapabilities" is the best name. Perhaps something along the lines of "MethodChoices" or "PaymentChoices". What is being registered is a payment option for the user to select, with some filtering constraints, such as methods and capabilities, that the browser surfaces in some way. I'm thinking of it primarily from the perspective of a PaymentHandler developer -- and what they are trying to surface for their users.

However, I could be convinced that "MethodCapabilities" is an acceptable name.

**Comment by anthonyvd** [comment]
I think the proposal here is to move away from a world where the Payment Handler defines a set of instruments/hints and instead declares what types of payments it can process. Chrome already only uses the instruments for that purpose (capabilities matching) and we don't display instruments (only the single PaymentManager's userHint might eventually be displayed). We don't plan on letting the user select anything more granular than the Payment Handler and instead will defer instrument selection to the Handler through openWindow. This seems consistent with what other implementers are looking at doing too.

As far as the name is concerned, Ian and I were also not 100% satisfied. We came up with PaymentMethod (which was already used in the Payment Request spec) and SupportedMethod (which isn't super reusable elsewhere in the spec if it comes back without a being in a "this is supported" context). Suggestions welcome!

**Comment by dlongley** [comment]
@anthonyvd,

> I think the proposal here is to move away from a world where the Payment Handler defines a set of instruments/hints and instead declares what types of payments it can process.

Ok, I see. In that case, exploring even further changes to simplify the API may be worthwhile. I don't see a reason to have a PaymentInstruments "container" that is "map-like". Perhaps this should instead be a single configuration call that would also provide a place for specifying icons, the "user hint", and so on:

```js
await registration.paymentManager.configure({
  icons: ['...'],
  userHint: '...',
  supportedMethods: [{
    method: 'basic-card',
    capabilities: {
     supportedNetworks: ['visa'],
     supportedTypes: ['credit']
    }
  }, {
    method: 'https://bobpay.com/'
 }]
});
```

**Comment by anthonyvd** [comment]
@dlongley That looks good. What's the `icons` field for? It kind of made sense in the context of 1 icon per instrument, I'm not sure it's relevant in this new set up (the Handler itself has an icon defined in its manifest).

**Comment by dlongley** [comment]
@anthonyvd,

> What's the icons field for? It kind of made sense in the context of 1 icon per instrument, I'm not sure it's relevant in this new set up (the Handler itself has an icon defined in its manifest).

It may not be needed. I didn't want to mistakenly leave anything out in the proposal.

In trying to take a payment handler developer perspective, it may be pleasant to update everything in one spot for each handler. But in #178 it does seem that browser vendors may prefer to only pull icons from the web app manifest via the page that registered the handler.

**Comment by rsolomakhin** [comment]
`paymentManager.configure()` seems sensible.

**Comment by ianbjacobs** [comment]
I am closing this issue as SRC discussions make instrument level displays an interesting topic.
