### ISSUE TITLE
Just in time installation of Payment Handler

### ISSUE THREAD

**Issue by majaybabu** [w3c/webpayments-payment-apps-api#303]
If Payment Request has both "basic" and a "payment method" then only "basic" is displayed if the "payment method" is not installed before. Is there a way "payment method" can also be displayed along with "basic" cards and if user chooses "payment handler" option the SW gets installed right then and the user can pay with the "payment handler". 

We have not tested this - But what happens when there are 2 "payment methods" on the Payment Request and one of the Payment handler is installed but the other is not installed and is the default_application on payment-manifest. Does the payment sheet display both the Payment methods then ?

**Comment by gogerald** [comment]
For efficiency, Chrome will only crawl and show not installed (JIT) payment handler if there is no installed payment handler for a payment request. For ‘basic-card’, users can always add one, so we do not crawl JIT. Note that JIT is not part of the spec, so other browsers may or may not support it.

**Comment by majaybabu** [comment]
Is that true even when both the payment handlers are part of the same payment-manifest/payment method. Lets say one of the payment handler on the payment manifest is installed but the other which is marked as the default_application is not installed.  In that case does the Payment sheet show only the installed Payment handler or both Payment handlers are displayed.

When there are 3 Payment methods (each having one Payment handler) on Payment Request and none of those 3 Payment handlers are installed but they are the default_applications then all 3 Payment handlers will be shown on the Payment sheet correct ?

**Comment by gogerald** [comment]
1/  only the installed payment handler
2/ correct

**Comment by ianbjacobs** [comment]
Closing this as it seems the question was answered. We can reopen if necessary.
