### ISSUE TITLE
What mechanism allows enforcing payment handler authenticity?

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#308]
From [TAG review](https://github.com/w3ctag/design-reviews/issues/231#issuecomment-377645336):

> [8.4 Payment App Authenticity](https://w3c.github.io/payment-handler/#payment-app-authenticity) sounds good, but it's not clear if this specification describes a mechanism that allows it to be enforced. More detail would be helpful.

We should mention that payment handlers are identified by service worker scopes, origins of which are compared to the origins of payment method identifiers and the entries in the `"supported_origins"` list in the payment method manifest.

cc @dbaron

**Comment by ianbjacobs** [comment]
@rsolomakhin and I made edits to the spec and the good practices wiki and so are closing this issue.
