### ISSUE TITLE
CanMakePaymentEvent handling algorithm unclear

### ISSUE THREAD

**Issue by danyao** [w3c/webpayments-payment-apps-api#330]
The current specification for `CanMakePaymentEvent` handling in the Payment Handler API is unclear in light of the `canMakePayment`/`hasEnrolledInstrument` change in Payment Request API [1][2].

First, the new `canMakePayment` is meant to represent the existence of support without checking available instrument. So perhaps `CanMakePaymentEvent` should not be dispatched at all in this case.

Second, if `CanMakePaymentEvent` should be dispatched for `hasEnrolledInstrument`, the current algorithm [3] is unclear about the return value when the steps are terminated early:
> 4.3 Handling a CanMakePaymentEvent
Upon receiving a PaymentRequest, the user agent MUST run the following steps:
> 1. If user agent settings prohibit usage of CanMakePaymentEvent (e.g., in private browsing mode), terminate these steps.
> 2. Let registration be a ServiceWorkerRegistration.
> 3. If registration is not found, terminate these steps.

Chrome's current implementation returns `true` if the early termination is triggered from step 1 or if it is triggered for just-in-time installable payment handlers from step 3. This will be the wrong answer if the website's intention is to check `hasEnrolledInstrument`.

I think it will make more sense to clarify in the spec these two changes:

- `CanMakePaymentEvent` is only dispatched when website queries `hasEnrolledInstrument`
- Implementations should return `false` when `CanMakePaymentEvent` cannot be dispatched, either due to private browsing mode or if the payment handler is not installed.

[1] https://github.com/w3c/payment-request/pull/806
[2] https://lists.w3.org/Archives/Public/public-payments-wg/2018Nov/0018.html
[3] https://w3c.github.io/payment-handler/#handling-a-canmakepaymentevent

**Comment by rsolomakhin** [comment]
These suggestions sound good.

By the way, user agents generally try to prevent websites from detecting whether the user is in private browsing mode. I can't think of a way to detect private browsing mode by checking for `false` return value from `pr.hasEnrolledInstrument()`. If you think this could be a problem, let me know and we can note it in the spec.

**Comment by danyao** [comment]
Thanks for raising the private browsing mode point. Maybe there is a problem. If a website has control of a payment handler, then it can detect whether user is in private browsing mode by calling hasEnrolledInstrument and checking if the result if false.

Can payment handlers be installed silently without user action? I feel this is the worst case because user may not know they are tracked this way.

**Comment by rsolomakhin** [comment]
Very interesting attack vector! We can mitigate this by short-circuiting the `hasEnrolledInstrument()` algorithm when the merchant and the payment handler are from the same origin. In that case, we can fire the `CanMakePaymentEvent` without any privacy violations, because it's a single origin communicating to itself. This behavior would be the same for both regular and private browsing mode, thus removing the possibility of detection of private browsing mode.

**Comment by danyao** [comment]
That's a good idea. It doesn't fully plug the hole though because a malicious website can host the payment handler on a different origin.

**Comment by rsolomakhin** [comment]
Would a visual indicator in the user agent help?

**Comment by danyao** [comment]
A visual indicator would be useful for other reasons, but I doubt that it'll be effective in communicating the nuance: "the current website is querying hasEnrolledInstrument() on payment handler X and can use this as a way to detect that you're in private browsing mode". It also doesn't actually stop the detection.

It seems we're stuck between two privacy requirements:
1) In private browsing mode, don't signal payment handler about user's current presence on a website.
2) The absence of the signal actually allows a website to detect that user's in private browsing mode.

The same-origin short-circuit you suggested may cut off most of the abuse. But I don't have a good mental model of how a website can abuse the knowledge that user is in private browsing mode, so not sure if that is sufficient. It'll be good to get our privacy team's take on it.

**Comment by rsolomakhin** [comment]
If we had to choose only one, then (1) takes priority over (2), because (1) leaks way more information to the payment handler (merchant's origin, for example) than what (2) reveals to the merchant---the one bit about the user being in private browsing mode.

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin and @danyao,

Thanks for the good discussion. Some thoughts:

- If the CanMakePaymentEvent is only triggered by hasEnrolledInstrument and not PR.canMakePayment, then it seems we should change the name in Payment Handler
to HasEnrolledInstrumentEvent. 

- I am trying to understand this sentence: "If a website has control of a payment handler, then it can detect whether user is in private browsing mode by calling hasEnrolledInstrument and checking if the result if false." Is this what you mean: Merchant controls origin of PR API call and also the payment handler. By calling PR.hasEnrolledInstrument and getting a value of 'false' back, and by knowing in the payment handler that the user actually does have an enrolled instrument, then the merchant knows the user is in private browsing mode.

If so, +1 to asking the privacy folks. :)

Ian

**Comment by rsolomakhin** [comment]
@ianbjacobs wrote:

>  Is this what you mean...

Yep, your understanding is correct!

**Comment by danyao** [comment]
> * If the CanMakePaymentEvent is only triggered by hasEnrolledInstrument and not PR.canMakePayment, then it seems we should change the name in Payment Handler
>   to HasEnrolledInstrumentEvent.

+1 to renaming to HasEnrolledInstrumentEvent.

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin and @danyao,

I hunted around and found this documentation [1], which says "In Firefox, Service Worker APIs are also hidden and cannot be used when the user is in private browsing mode." I don't know if that's the same for other implementations.

If I understand this correctly, this would mean that a Web-based payment handler would not be available at all in private browsing mode. That might mean that this issue is a non-issue.

I still don't know but thought that one way to "address" this issue is to make it a non-issue through other means. :)
Ian

[1] https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by rsolomakhin** [comment]
Chrome does not hide the Service Worker API in private browsing mode  :-(

**Comment by ianbjacobs** [comment]
Per discussion today our current expectation is to add a security consideration to the specification.
