### ISSUE TITLE
Working example/demo Web Payment App

### ISSUE THREAD

**Issue by richardPAG** [w3c/webpayments-payment-apps-api#336]
Just wondering if a working version of the Web Payments [example](https://rsolomakhin.github.io/pr/skip-ui/) App is anywhere?

I think the spec has evolved to change Supported Instruments from an array to a string?

Also not sure if there is another client that invokes the Alipay logic?

**Comment by ianbjacobs** [comment]
@richardPAG, is this what you are looking for?
 https://bobpay.xyz/

**Comment by richardPAG** [comment]
@ianbjacobs  Maybe I need a user's guide but what does it do apart from (un)register a service worker?

Something to buy? A "Buy" button?

**Comment by ianbjacobs** [comment]
The payment handler demo just illustrates the registration and launch procedures, and allows you to return some fictitious payment method data from a fictitious account.

**Comment by rsolomakhin** [comment]
@richardPAG : You may be able to run the Google Pay payment handler at https://rsolomakhin.github.io/pr/gp/ .

**Comment by richardPAG** [comment]
Cool! Thanks @rsolomakhin . Where can I find the source code for that?

PS. You might want to have someone update the links [here.](https://www.w3.org/Payments/WG/)

**Comment by ianbjacobs** [comment]
@richardPAG, good suggestion.

On the WG home page there is a link to code examples [1]. That page already linked to MDN and I've added a link there to Rouslan's examples.

Ian

[1] https://github.com/w3c/payment-request-info/wiki/CodeExamples

**Comment by rsolomakhin** [comment]
> Where can I find the source code for that?

Follow the breadcrumbs of `curl --head https://google.com/pay` according to steps in https://w3c.github.io/payment-method-manifest/#fetch-pmm

**Comment by richardPAG** [comment]
Good stuff! Thanks
