### ISSUE TITLE
CANIUSE for download-free/bundled Payment Methods 

### ISSUE THREAD

**Issue by richardPAG** [w3c/webpayments-payment-apps-api#338]
I forget which video I saw it on (Google I/O?) but the gist was that Chrome was collaborating with Payment Providers (PayPal?) to bundle all the payment functionality required with the installation of the Chrome UA. IOW, the Payment Handler manifest feature of identifying sites to download respective payment apps would be redundant.

Firstly, can someone please confirm that?

Secondly, is there somewhere, similar to caniuse.com, that will have an up to date list of browsers and Payment Providers that support same?

Clearly, it is a much more desirable UX for the user not have to download the merchants Payment Handler software to make a purchase.

**Comment by ianbjacobs** [comment]
@richardPAG, I don't know anything about bundling. If you have a reference, that would help.

Regarding maintaining a list of payment handlers that work with Payment Handler API, we don't have one currently. (We also don't have a list of Android Payment Handlers that work with Chrome.) I could see maintaining a list in the very short run to raise awareness, but I would not want to maintain a list in the long run.

**Comment by richardPAG** [comment]
Sorry for the delay @ianbjacobs it took a while to find it. It's from [Google I/O '17](https://www.youtube.com/watch?v=hU89pPBmhds) starting at 33:00 and PayPal was correct. (If I was there I would've clapped!)

As this was 2 years ago it should either be bearing fruit or dead I guess?

It would be great if someone maintained a list but, like you, I'm not volunteering :-)

**Comment by ianbjacobs** [comment]
@richardPAG,

My read of the Google I/O comment is that discussions about Web-based payment handlers were happening. Those sorts of conversations (with lots of parties) are ongoing since we are still in the early phases of the world of payment handlers.

**Comment by richardPAG** [comment]
What did Zach Koch say?

**Comment by ianbjacobs** [comment]
@richardPAG,

I didn't seek out Zach for the question; I just observed that what was said at Google I/O is consistent with ongoing outreach we have going on to raise awareness about and spur adoption of payment handlers.

**Comment by richardPAG** [comment]
C'mon @ianbjacobs! Not sure if you're gas-lighting me or we're looking at different videos?

Ok, I may have gone a bridge-to-far by using the word "bundling" but he clearly states that Chrome and PayPal are working on an integration sans any native App!

Go back to 32:28 on the I/O video and he draws attention to the "bit of irony" that the first integration of the Web Payment API is with native apps. This is just after the very good AliPay demo.

Zach goes on to exclaim the virtues and "Great News" about **PURE** Web App support due to the "really compelling" reasons.

Furthermore he identifies a user's choice of Payment Provider not correlating to native apps they have installed.

As an absolute minimum Zach is describing a Javascript library for PayPay to W3C Payment Request API integration. (Include a <script>) as opposed to links to download a native app.

So what has happened down this road since 2017?

ps. As a guy that went through High School in Perth called "Dick" (still to this day) I empathize with Zach's English-translation-pronunciation of his surname.  Plinty of Yarpie Rugby/Cricket players etc called De Koch.

**Comment by marcoscaceres** [comment]
@richardPAG, we don’t have the information you are looking for. You can reach out to someone at Google directly.
