### ISSUE TITLE
broken links in definitions of attributes of PaymentRequestEvent

### ISSUE THREAD

**Issue by dbaron** [w3c/webpayments-payment-apps-api#355]
While trying to review w3ctag/design-reviews#425, I was trying to understand some of the related specs, one of which is this one.  I stumbled across a pile of broken links that made the spec rather hard to understand.  The ones I ran into were in [5.3.10 shippingOptions attribute](https://w3c.github.io/payment-handler/#shippingoptions-attribute), but I would note that at least the previous section appears to have similar problems.  In particular, this section has three links, the first two of which appear to point to the wrong things:
* the link to `ShippingOptions` points back to this section when it appears intended to point to something else
* the link to [`PaymentDetailsInit`](https://www.w3.org/TR/payment-request/#paymentdetailsinit-dictionary) points to something that doesn't have a `ShippingOptions`, when it seems like it ought to.

(The third link really just points to the same thing as the second link with an extra level of indirection.)

This sort of thing makes it hard to understand how these specs fit together...

**Comment by sahel-sh** [comment]
Thank you @dbaron for your feedback, and I apologize for the inconvenience.

> While trying to review [w3ctag/design-reviews#425](https://github.com/w3ctag/design-reviews/issues/425), I was trying to understand some of the related specs, one of which is this one. I stumbled across a pile of broken links that made the spec rather hard to understand. The ones I ran into were in [5.3.10 shippingOptions attribute](https://w3c.github.io/payment-handler/#shippingoptions-attribute), but I would note that at least the previous section appears to have similar problems. In particular, this section has three links, the first two of which appear to point to the wrong things:
> 
> * the link to `ShippingOptions` points back to this section when it appears intended to point to something else

I will fix this instance and revise the spec to make sure that all links are pointing to the intended locations. 

> * the link to [`PaymentDetailsInit`](https://www.w3.org/TR/payment-request/#paymentdetailsinit-dictionary) points to something that doesn't have a `ShippingOptions`, when it seems like it ought to.
> 
> (The third link really just points to the same thing as the second link with an extra level of indirection.)

shippingOptions is a member of [`PaymentDetailsBase`](https://www.w3.org/TR/payment-request/#dom-paymentdetailsbase) which  [`PaymentDetailsInit`](https://www.w3.org/TR/payment-request/#paymentdetailsinit-dictionary) inherits from. I will rewrite the sentence to make it clear.
> 
> This sort of thing makes it hard to understand how these specs fit together...

**Comment by marcoscaceres** [comment]
@ianbjacobs, we should republish Payment Request API and then allow ReSpec to automatically fix the broken links (via `xref`). Otherwise, any fixes that @sahel-sh makes will just risk breaking again.

**Comment by ianbjacobs** [comment]
@marcoscaceres.

Can you point me at a snapshot of PR API to request republishing? And is it the case that all changes are editorial? 

Thanks!
