### ISSUE TITLE
The "triggered by user activation" link is incorrect

### ISSUE THREAD

**Issue by maxlgu** [w3c/webpayments-payment-apps-api#358]
Currently it's pointing to a non-existing section of the doc. Should it link to https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation instead?

**Comment by marcoscaceres** [comment]
We should probably wait and see how Service Worker's [`openWindow()`](https://w3c.github.io/ServiceWorker/#clients-openwindow) gets updated to use the new model.
