### ISSUE TITLE
iDeal test payment- TRXID is not requested in my webpage's URL

### ISSUE THREAD

**Issue by muzammilmuzamil** [w3c/webpayments-payment-apps-api#359]
I am Unable to access trxid from requested test payment ..
please help how can a get the trxid in my variable?

Test payment generate correct transactionID=****** but when it returns to my page trxid is not accessed successfully.

![ad](https://user-images.githubusercontent.com/59788565/72215930-d6203900-353b-11ea-9a76-c917895a3872.JPG)

//IDEAL CHECK
if(isset($_REQUEST['trxid'])) {

$trx = $_REQUEST['trxid'];

$bbdata = array(
    'rtlo' => '151309',
    'once' => 1,
	'trxid' => $trx,
	'once' => 1
);
 
// send a request to example.com (referer = jonasjohn.de)
$iresult = PostRequest(
   "http://www.targetpay.nl/ideal/check",
    "http://www.gambinospel.nl/test/",
    $bbdata
);

**Comment by rsolomakhin** [comment]
Hi @muzammilmuzamil ! This appears to not be related to the [Payment Handler API](https://w3c.github.io/payment-handler/). I'm closing this as WontFix. Please re-open if I misunderstood.
