### ISSUE TITLE
Creating a "Wallet" using PaymentHandler?

### ISSUE THREAD

**Issue by cyberphone** [w3c/webpayments-payment-apps-api#368]
It is clear that `PaymentHandler` should work for major payment providers like PayPal who have their own payment button in checkout forms.

Now, imagine a world with potentially thousands of independent payment providers.  Using the current specification this would force merchants relying on the browser's built-in selection mechanism.  Since each provider would need to supply their own `PaymentHandler` code, this scheme will likely contribute to _fragmentation_ rather than standardization.

This contrasts to native payment handlers like Apple Pay where a single instance of the client software can support multiple payment providers.

Example running on desktop browsers: https://cyberphone.github.io/doc/saturn/ui-demo

_Disclaimer_: I'm not an expert on `PaymentHandler` or `ServiceWorker`.

**Comment by ianbjacobs** [comment]
Closing this as this is not an issue on the specification.

**Comment by cyberphone** [comment]
If my findings are correct (_which I don't know for since I'm not an expert on this_), the specification suffers from limitations that may need to be dealt with.
@marcoscaceres @rsolomakhin @danyao

**Comment by cyberphone** [comment]
As a comparison, the payment method the WG started with (`basic-card`), has all the characteristics of an issuer- and domain-independent wallet, at least as implemented in Chrome.
@adrianhopebailie
