### ISSUE TITLE
How can a Browser-based Payment App cancel the payment flow?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#37]
Migrated from 
 https://github.com/w3c/webpayments/issues/128

**Comment by adamroach** [comment]
The current service worker proposal addresses this with:

> The user agent receives a failure response from the payment app through rejection of the Promise. The user agent **MUST** use the rejection reason to reject the Promise that was created by `PaymentRequest.show().` 

I _think_ that should d be sufficient for canceling the payment flow, although it's possible I've overlooked something.

**Comment by rsolomakhin** [comment]
Can we let the user select a different app, if one of the apps fails?

**Comment by ianbjacobs** [comment]
At the 23 November 2016 task force call, there was support for not prohibiting a "retry with other matching payment app" behavior by the user agent.

http://www.w3.org/2016/11/23-apps-minutes.html

**Comment by tommythorsen** [comment]
I've added a PR that addresses cancellation here: https://github.com/w3c/webpayments-payment-apps-api/pull/72
