### ISSUE TITLE
Make Marcos repo admin

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-payment-apps-api#373]
@ianbjacobs or @adrianhopebailie, can you grant me super powers? Need it to manage branches and set up secrets in the settings.

**Comment by marcoscaceres** [comment]
*accidentally tab-completed to Adam instead of Adrian... fixed above.

**Comment by ianbjacobs** [comment]
I've given you Admin privileges. Thanks, @marcoscaceres!
