### ISSUE TITLE
Payment Instrument architecture clarification 

### ISSUE THREAD

**Issue by RomanKaliupin** [w3c/webpayments-payment-apps-api#381]
Hi all,

The BobPay payment method have two payment instruments - bobpay and basic-card. When the user select basic-card, enter needed data and press pay - we use the BobPay's service worker for handling of the rest of the flow (and same for BobPay instrument). Probably it is due to the fact that basic-card is build in instrument.

I want to create a custom Payment Web App with name (for ex.) CustomPay. I want that this app has two payment instruments, first CustomPay and the second NewPay.

**Q:** What should I do, in order to use NewPay service worker when the user select NewPay payment instrument? Could you please give an example? Or all payment logic (for all payment instruments) should be covered with CustomPay service worker? 

Thank you for your answer.
Roman.

**Comment by RomanKaliupin** [comment]
Hi all, 

Let me explain the question from more accurate point of view.

Let me introduce you a diagram of current behavior of BobPay: 
![BobPay](https://user-images.githubusercontent.com/71703038/101903225-a0a52500-3bbc-11eb-8819-d4fa5880342e.jpg)
Let me explain main points and problems of this approach (on my point of view).
The main problem is that Bob Pay and Basic Card payment instruments are handled on BobPay Payment Web App service worker. But I assume, It is, maybe, because basic-card is build in instrument.

Let me introduce you the architecture which seems to be logic (on my point of view).
![CustomPay (1)](https://user-images.githubusercontent.com/71703038/101903519-13ae9b80-3bbd-11eb-81f2-cfdf55fccca2.jpg)
There we have a CustomPay payment web app which includes NewPay and CustomCredit payment instruments. The main point is, that when user select NewPay (add needed data, or whatever) we send data to CustomPay service-wroker but than send request\message to NewPay service-worker in order to proceed with needed logic. After response from NewPay serice-worker, CustomPay serice-worker finalize payment or do whatever else. In this case, we assume that CustomPay service-worker it is a Web Server which interacts with 3rd parties.

**Question:** How to achieve this behavior or its analog in Payment Handler ? Is it possible?  

Best,
Roman.

**Comment by RomanKaliupin** [comment]
Hi @ianbjacobs , 
Hi @rsolomakhin ,

Could you please take a look on this issue?

Best Regards,
Roman.

**Comment by rsolomakhin** [comment]
Hi @RomanKaliupin,

The use case is not 100% clear, but it sounds like the single service worker solution should work. Is there anything wrong with that solution?

Cheers,
Rouslan

**Comment by RomanKaliupin** [comment]
Hi @rsolomakhin ,

Yeah, that solution should work.. but there we have two not logic points:
1. I can register a lot of payment instruments and for each I must have a service worker.. but i will never use that service worker in my logic. If you fallow single service worker approach - why i must have a service worker for each payment instrument?
2. Let's imagine that Google Pay can be used as payment instrument... should I implement whole logic of google pay (with accessing of all needed info from google) in my Payment Web App?


The use case the next - How to use service worker of payment instrument? 

Best Regards,
Roman.

**Comment by rsolomakhin** [comment]
Can you describe your use case a little bit more, please? I'm still confused.

> i will never use that service worker in my logic.

Why not?

> why i must have a service worker for each payment instrument?

That's not a requirement. One service worker can handle multiple payment instruments.

> Let's imagine that Google Pay can be used as payment instrument... should I implement whole logic of google pay in my Payment Web App?

That's one approach. Your payment handler window also can redirect to other origins or include HMTL/CSS/JS assets from other origins to provide the necessary functionality.

> How to use service worker of payment instrument?

The service worker must register an event listener for `paymentrequest` event. The browser will fire this event when the user selects your payment handler.

**Comment by RomanKaliupin** [comment]
Hi @rsolomakhin ,

>Your payment handler window also can redirect to other origins

How to accomplish this goal?

> include HMTL/CSS/JS assets from other origins to provide the necessary functionality.

How to accomplish this goal?

>Why not?

How from payment handler can be triggered service worker of available payment instrument? 

Best Regards,
Roman.

**Comment by rsolomakhin** [comment]
A payment handler window can redirect via `window.href = "https://google.com";`. Assets can be included via `<iframe>`, `<style>` and `<script>` tags.

> How from payment handler can be triggered service worker of available payment instrument?

A payment handler is special case of a service worker. Please read this tutorial: https://web.dev/payments/

**Comment by RomanKaliupin** [comment]
Hi @rsolomakhin ,

Thank you for sharing of this doc. I just went through this doc and there are no info about the case which I shared with you.

Just to clarify. My case is when one payment handler has several custom payment instruments. For making payment instrument available in payment handler I need to create a corresponding service worker and manifest. 
If to just redirect (from payment handler) to url which point on that payment instrument you will not appear on corresponding payment handler.

Payment handler A has B and C payment instrument. If from payment handler A redirect to payment handler B -> it will not open payment handler B. 
Could you please give an example of code which is work in this way?

Best,
Roman.

**Comment by ianbjacobs** [comment]
Hi @RomanKaliupin,

I am not sure to fully understand the requirements yet, but I appreciate your diagram and commands. I'll try to be helpful.

I think the following is true:

 * The Chrome implementation of Payment Handler API shows one name/logo pair per payment handler. This name/logo pair might be a payment app (e.g., "Google Pay") or it might be a payment instrument (e.g., "Visa *****4567"). 

 * If you wish for a name/icon to be shown in the browser's "sheet" (the selector of shipping address, contact information, and payment handlers), then you should create a payment handler for that name/icon. So if you want the user to see an instrument, you should create a payment handler just for that instrument.

 * For "add an instrument" you could thus create one payment handler with the appropriate name/icon. That payment handler's job would be to enroll new instruments.

 * If you redirect the user (in the "add" payment handler) to your origin (e.g., pay.com), then you can install a new payment handler for the newly added instrument. The job of that specific payment handler is to fulfill payments with that instrument.

 * The next time the user goes through payment request, the user will see that payment handler (for that specific instrument) in addition to the "add an instrument" payment handler.

Is that what you would like to do?

Ian

**Comment by rsolomakhin** [comment]
Perhaps it would be best to start with definitions. What do you mean by `payment instrument`? We have a definition here:

https://w3c.github.io/payment-handler/#paymentinstruments-interface

Is that what you had in mind?

**Comment by RomanKaliupin** [comment]
Yes.
For ex. BobPay payment instrument:
![image](https://user-images.githubusercontent.com/71703038/102130499-9d7a9500-3e59-11eb-8fb7-f8c10a77b753.png)

**Comment by rsolomakhin** [comment]
A demo of what @ianbjacobs described: https://rsolomakhin.github.io/pr/apps/src2/

**Comment by rsolomakhin** [comment]
The `registration.paymentManager.instruments.set()` can be called multiple times, as long as the instrument key is different every time. (If you re-use the same key, then the old data will be overwritten.) This enables one payment handler to have multiple instruments.

The `method: 'https://bobpay.xyz/pay'` parameter specifies the `"payment method identifier"`.

**Comment by RomanKaliupin** [comment]
Hi @ianbjacobs ,

Thank you for your explanation.
>That payment handler's job would be to enroll new instruments.

By enroll new instrument you assume the next construction:
![image](https://user-images.githubusercontent.com/71703038/102132008-bab06300-3e5b-11eb-9e58-f96a70256210.png)

>If you redirect the user (in the "add" payment handler) to your origin (e.g., pay.com), then you can install a new payment handler for the newly added instrument.

I'm I right understand you? From "add" payment handler (payment handler which should just display payment instruments) I need to redirect user to my origin "pay.com"?  Could you please share the demo?

Hi @rsolomakhin the demo which you shared with me just present two **separate**  custom payment handlers. My goal is to be able to have these custom payment handlers in the another payment handler.

What I want to achieve: 
Payment Handler **A** has two instruments **B** and **C** (each of mentioned instruments links on corresp payment handler in **method** attr). When user open payment handler **A** and click on payment instrument **B**, user redirects to payment handler **B**. 
Could you please let me know if it is clear?

Best,
Roman.

**Comment by RomanKaliupin** [comment]
Hi @rsolomakhin ,

Could you please clarify several points about  https://rsolomakhin.github.io/pr/apps/src2/  example?
From what I found, after pressing **Install** button, we perform redirect two times, and on each page add corresponding manifest and register corresponding service worker, right (and third redirect to come back)?

So, my question is - how to do it without performing of redirection each time when I want to register a new payment handler  app ?
I tried with iframes. And was able to register a service worker, but not manifest (the name and icon of payment wasn't appeared).

Best,
Roman.

**Comment by rsolomakhin** [comment]
Hi @RomanKaliupin, 

The manifest is tied to the top-level context, so iframes would not work, sorry. At this time, the relationship is one manifest <<-->> one URL. Since payment handler name and icon come from the manifest file, that means that different icons and names must live in different manifests that are linked from different URLs.

Cheers,
Rouslan
