### ISSUE TITLE
navigator.credentials.get does not resolve promise when called from the window opened by PaymentRequestEvent.openWindow

### ISSUE THREAD

**Issue by apouillard** [w3c/webpayments-payment-apps-api#390]
First issue creation for me: sorry if it's not the correct place to create it but I can't tell where the issue origin lie and identify a specific thematics...

With Chrome, my existing web payment app demos that used to call webauthn API for user authentication don't work any more. I've tried to find the reason why and finally noticed the following behaviour :

- When called from a page loaded in the browser main window, navigator.credentials.get() contained in my code resolves a promise
- The same page called from a window opened by PaymentRequestEvent.openWindow causes the promise pending and never be resolved.

Any idea about the cause ? a new flag to set in chrome, chrome updates linked to SPC, webauthn or payment handler ...

**Comment by rsolomakhin** [comment]
Hi, this sounds like it could be a Chrome issue, so the correct place for this is in https://crbug.com/new. Please file the bug report there and link to it from here.

**Comment by apouillard** [comment]
Bug report submitted, thanks Rouslan
