### ISSUE TITLE
InstrumentKey availability

### ISSUE THREAD

**Issue by apouillard** [w3c/webpayments-payment-apps-api#391]
The last pusblished version of Payment Handler API specification describes instrumentKey as an attribute of the PaymentRequestEvent.

The specification also mentions that InstrumentKey can be set to an empty string meaning that the user did not choose a specific PaymentInstrument : 

-  Why this exception ? Does the "empty string" case correspond to the skip-the-sheet event ? Even if the selection is implicitly done by the browser and not explicitly by the user, the instrumentKey remains a useful information: for example it could allow the instrument issuer to clearly identify the selected payment instrument amongst others owned by the customer ...
- What is the correct way to retrieve the instrumentKey from the PaymentRequestEvent ? I've tried with different browsers and never managed to get the value.

Any help/clarification would be appreciate

**Comment by rsolomakhin** [comment]
Hi @apouillard . We decided against `instrumentKey` in the end. That text needs to be removed from the spec. Pull requests are welcome 😀

**Comment by ianbjacobs** [comment]
@rsolomakhin, I'm happy to do a pull request. Just to check on what would need to change:

* 3.3 What's left of the PaymentInstruments interface?
* 5.3.7 Delete instrumentKey member
* 5.3.11 PaymentRequestEventInit dictionary. Delete instrumentKey member
* 5.5 remove instrumentKey from algorithm

Anything else?
Ian

**Comment by rsolomakhin** [comment]
@ianbjacobs for now let's start with only removing `PaymentRequestEvent.instrumentKey` from https://w3c.github.io/payment-handler/#the-paymentrequestevent.

Let's leave section 3.3 intact until we've given it some more thought, sound OK?
