### ISSUE TITLE
Remove the deprecated basic-card content

### ISSUE THREAD

**Issue by maxlgu** [w3c/webpayments-payment-apps-api#397]
The spec still mentions basic-card although basic-card has been deprecated, e.g., 
* "Some payment methods, such as basic-card expect little to no processing by the payment handler which simply returns payment card details in the response"
* "For example, for the basic-card payment method, this object will consist of an object with two fields: one for supportedNetworks, and another for supportedTypes."
* code example of payment handler registration, registering capabilities

As a result, we should remove the deprecated basic-card content.

**Comment by maxlgu** [comment]
@rsolomakhin

**Comment by rsolomakhin** [comment]
Yes, please!
