### ISSUE TITLE
What is the process for rendering the payment app UI

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#4]
Question raised at London f2f and migrated from: https://github.com/w3c/webpayments/issues/162

When the payment app requires UI it provides a URL that must be fetched to render UI.

WebRTC does this by rejecting the original calling page's promise with a URL which is rendered.
This seems like a problem (asking the merchant to render the app).

Better option may be a simple `window.open()` from the payment app javascript code.

**Comment by ianbjacobs** [comment]
This is addressed in AdamR's proposal (soon to be merged) for browser-based payment apps with PaymentWindow.

Ian
