### ISSUE TITLE
Native app flow doesn't work in chrome 130

### ISSUE THREAD

**Issue by AdaltonLeite** [w3c/webpayments-payment-apps-api#421]
Hi guys, 

I'm doing some tests with Payment Handler and updating Chrome to version **130** this morning causes the browser to no longer take me to the app with payment handler API, have we had any changes in Chrome that may have impacted this project? I looked at the release notes and didn't see anything specific. 

Even if we use the example application([BobBucks](https://bobbucks.dev/)), we can see that it now only leads to the mobile web flow and no longer to the app's authentication flow. 

CC: @rsolomakhin

**Comment by rsolomakhin** [comment]
Hi @AdaltonLeite,

This behavior is not expected. Could you please either file an issue on https://crbug.com/new and/or reach out to `rouslan <at> google <dot> com` to schedule a meeting for live troubleshooting? Thank you.

Sincerely,
Rouslan

**Comment by AdaltonLeite** [comment]
Thanks @rsolomakhin, I create this issue: https://issues.chromium.org/issues/377620713

**Comment by AdaltonLeite** [comment]
@rsolomakhin I'm closing this ticket as we've already dealt with the issue above. Thank you very much
