### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-payment-apps-api#45]
Has versioning of payment applications or methods been considered?

So for example, what happens when SEPA Credit Transfer is enhanced to V2? How does a merchant website know the implementation is V1 or V2?

**Comment by adamroach** [comment]
I think the discussions we had so far was that new versions would be new payment method IDs.

e.g.:

`https://www.example.com/ferretpay/v1` versus `https://www.example.com/ferretpay/v2`
and
`basic-card` versus `basic-card-v2`

Apps indicate which payment methods -- including versions -- they support. They find out in the response which version has been used.

**Comment by ianbjacobs** [comment]
@mattsaxon, do you still think this question bears on the payment apps spec, or can we close it in this forum? 

I have added a (currently small) section on versioning to the payment method good practices spec:
 https://w3c.github.io/webpayments/proposals/method-practice/#versionin

**Comment by ianbjacobs** [comment]
Hi Matt,

I'm closing this based on my understanding that:

* Payment methods can be versioned (with new identifiers)
* Payment apps can be versioned with (new identifiers)
* Merchants and payment apps can declare support for multiple verisons.

We can reopen if this proves insufficient.

Ian
