### ISSUE TITLE
Pass along a Transaction ID

### ISSUE THREAD

**Issue by halindrome** [w3c/webpayments-payment-apps-api#47]
I believe that users of Payment Apps would benefit from their App(s) being able to know more about each transaction that is processed.  One way to facilitate this is to include a transaction ID in the PaymentAppRequestData item.  

I would be happy to provide a PR if the group is open to this suggestion.

Note: This assumes that the group agrees with my suggestion in https://github.com/w3c/browser-payment-api/issues/287 that a transaction ID can be supplied by the merchant in the first place.

**Comment by ianbjacobs** [comment]
Hi Shane,

I believe that the current specification handles this proposal as follows:
- If the data would become part of the "top-level" data it would get passed along as being specific to the transaction.
- If the data would become part of the method specific data, it would be passed along in that data.

So I don't think additional changes are required to this specification.

Ian

**Comment by adrianhopebailie** [comment]
@ianbjacobs - in this case: 

> If the data would become part of the "top-level" data it would get passed along as being specific to the transaction.

The addition of the member to the "top-level" implies adding it to the `PaymentRequestData` dictionary [1]

[1] - https://w3c.github.io/webpayments-payment-apps-api/#sec-app-request-data

**Comment by rsolomakhin** [comment]
I prefer making this payment method specific.

**Comment by adrianhopebailie** [comment]
See https://github.com/w3c/browser-payment-api/issues/287

**Comment by halindrome** [comment]
@adrianhopebailie yes, the PaymentRequestData dictionary.  Thanks.

**Comment by ianbjacobs** [comment]
The current state of WG discussion about transaction ID suggests there will be a transaction ID. If the transaction ID is provided by the merchant, then it will be included in the payment method-specific data already required by the spec (so no changes required). if the transaction is generated by the user agent, then the spec will need to be updated so that the UA passes it to the app.

**Comment by ianbjacobs** [comment]
I am going to close this issue because I believe it is being dealt with in the main WG discussion:
 https://github.com/w3c/browser-payment-api/issues/224#issuecomment-263995469
