### ISSUE TITLE
Pictures would help!

### ISSUE THREAD

**Issue by halindrome** [w3c/webpayments-payment-apps-api#49]
The relationship between the Payee / Payee collection of accepted payment methods, the mediator, the payment app(s), the payment payment options, and the installed / defined payment methods is complex.  I diagram showing the hierarchy might be helpful!

**Comment by ianbjacobs** [comment]
Note: MattS may create a diagram based on today's task force call:
 https://www.w3.org/2017/04/04-apps-minutes#item05

**Comment by ianbjacobs** [comment]
Started work on this:
https://github.com/w3c/webpayments-payment-apps-api/pull/132

**Comment by ianbjacobs** [comment]
I'm going to close this issue for now (since there are diagrams in the spec). Can reopen later as the spec progresses.

Ian
