### ISSUE TITLE
Display may be subject to user and local policy (consider UA making security decisions etc)

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#5]
Raised at London f2f and migrated from: https://github.com/w3c/webpayments/issues/161

**Comment by ianbjacobs** [comment]
@adrianhopebailie,

I do not recall what this issue is about, and I don't find it obviously in the London minutes. Can you recall?

Ian

**Comment by ianbjacobs** [comment]
Closing this since no reply. Feel free to reopen if you feel it is important, but please add context if you do.
