### ISSUE TITLE
Links to terms and common terminology

### ISSUE THREAD

**Issue by halindrome** [w3c/webpayments-payment-apps-api#50]
This spec is pretty good about using terms consistent with those of other specs in the space.  It would be nice if those terms could be linked to their common definitions.  For example, the introduction uses the term "payment methods" but that is not really defined in the document.  There are many other examples like this.

**Comment by ianbjacobs** [comment]
I am closing this issue since the specification has evolved significantly. We may well need to review terminology, but given the state of the spec, I would welcome more specific comments.
