### ISSUE TITLE
Section 6 steps 1-5 seem to avoid selecting a payment option / payment method

### ISSUE THREAD

**Issue by halindrome** [w3c/webpayments-payment-apps-api#56]
It is not clear to me from the description where in the flow the payment option is selected.  Is this managed by the Payment App?  By the user agent based upon its list of available options?  By a window the payment app displays through the user agent?  I think we need to define who is in charge of the user interface at the time of the payment method selection very precisely.

**Comment by ianbjacobs** [comment]
My expectation is that the user agent is in charge of the selection UI. This applies both to payment request API as-is, and what we describe in the payment apps spec.

If we pursue payment apps as described by that spec, there will be richer UX. We are are discussing that in the payment apps task force.

For payment request API, it is not clear to me that more needs to be said (at this time).

Ian

**Comment by halindrome** [comment]
Note that, related to this, section 7.4 PaymentAppOption dictionary implies that the PaymentAppOption is passed in to the payment app from the mediator.  That's fine... let's clarify it.

**Comment by rsolomakhin** [comment]
Please note that I am more in favor of avoiding payment options at least
for v1. IMHO, they introduce an extra layer of complexity without tangible
benefits.

**Comment by halindrome** [comment]
@rsolomakhin just to clarify, are you saying you don't want "payment options" or "payment methods"?

**Comment by rsolomakhin** [comment]
I don't want payment options, e.g., "BobPay Visa_1111" and "BobPay
MasterCard_5454". I would rather just have payment apps for now, e.g.,
"BobPay".

**Comment by ianbjacobs** [comment]
I am closing this issue:

1) The User Agent is in charge of the display at the time of user selection of payment apps / options
2) The payment apps is then launched and may open its own display for user interaction; see also https://github.com/w3c/webpayments-payment-apps-api/issues/73

Ian
