### ISSUE TITLE
Users MUST be able to prevent the display of unregistered payment apps

### ISSUE THREAD

**Issue by halindrome** [w3c/webpayments-payment-apps-api#59]
In section 9.1 there are a number of requirements on user agents.  I believe that users MUST be able to opt out of being notified about unregistered payment apps.

**Comment by rsolomakhin** [comment]
This feels like a UX requirement. I am sceptical about introducing this
kind of UX requirements on user agents. UX is the best way for user agents
to differentiate.

**Comment by halindrome** [comment]
I agree that it feels like a UX requirement.  But we have LOTS of those in that section.

**Comment by burdges** [comment]
Agreed in principle.  :)  I haven't completely understood your choice of the word "notified" here though.  

It's clearly bad if a user can be tricked into invoking a payment app, like say by only offering that app.  In that case, a fraudulent website can harvest financial account details by requiring a payment app that looks like one from some company the user trusts.  And the user think that payment app shields their financial account details from this unknown webste. 

Are you envisioning that users concerned about such attacks should block unknown payment apps?  I donno if that is strong enough really, probably you need payment app registration to be something moderately involved for all users.

**Comment by halindrome** [comment]
Actually, @burdges , none of your examples are things I was envisioning.  And I used "notified" advisedly.  I don't like the word "displayed" as it implies a certain modality.  We are all about A11Y at the W3C!

My concern is this: Tom has chosen a Payment App as his payment representative on the Web.  Everything Tom does with regard to payments is done through that App.  All of his payment methods, loyalty cards, gift cards, digital offers, etc. are known to that App.  Tom does NOT want to ever use another Payment App.  Why should Tom be presented with Payment App options that he has not installed and never will.  He should just be sent to his payment app with his payment methods and be done with it.

Better yet, in the brave new world where Tom's payment app is very , very smart... that app is choosing his payment method for him.  He has told it that for domain X always use method Y.  Or he has said "whenever possible use method z at office supply stores because it gets me the most points.  At grocery stores use method w.  If methods z or w are not accepted.... prompt me."  

This is the sort of power that we are able to give to end users.  Spamming them with some web sites payment app when they already have these sorts of preferences available is just rude.

**Comment by ianbjacobs** [comment]
Hi all,

I propose to change:

 "The user agent MAY display recommended payment apps."

to:

"The user agent MAY display recommended payment apps. In this case, the user agent SHOULD also support configuration to not display recommended payment apps."

Ian

**Comment by ianbjacobs** [comment]
Closing with this edit:
https://github.com/w3c/webpayments-payment-apps-api/pull/70/commits/b852c8a5d6ad63e7799f8e305d57770a4f7b7105
