### ISSUE TITLE
Should we allow payment providers to issue queries about their installed payment apps (match on origin)

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#6]
Raised at London f2f and migrated from https://github.com/w3c/webpayments/issues/160

**Comment by ianbjacobs** [comment]
Relates notes:
- Payees can recommend their own payment apps, and browsers could display those higher in the list.
- Browsers could automatically elevate the position of a registered payment app from the same origin as the site the user is browsing.
- We have resolved that origin information (about the site of the purchase) should be available to payment apps, and so payment apps from the same origin can use that information for back channel communication.

In light of the last resolution in particular, I propose that we close this issue with no additional change (that is: no support for a query for merchants to learn if the user has registered their app).

**Comment by ianbjacobs** [comment]
I believe canMakePayment() is where we have landed on this topic:
 https://w3c.github.io/browser-payment-api/#canmakepayment-method

along with recommended payment apps.

Ian
