### ISSUE TITLE
Should payment apps implement payment method-specific filters?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#63]
Matt Saxon suggested to Ian that in the real world, payment method filtering is handled by payment apps, citing Apple Pay, Samsung Pay, Android Pay as examples.

One idea is to add to the payment app specification the following:
- Payment methods may define filtering capabilities.
- Merchants would include filter information in the 'data' object (of payment request API) for accepted payment methods
- Payments apps would be responsible for implementing matching using the filter information. Payment apps could choose not to implement filtering for a given payment method.
- There would be a standard function implemented by payment apps that would respond true or false to queries from the mediator about (filter) matching for each payment method.

Thus, payment method-specific filters would be implemented by payment apps, not the mediator.

Note: For in-browser basic card support, this can also be modeled as the browser-as-payment-app implementing matching rather than the browser-as-mediator.

**Comment by adamroach** [comment]
To capture some notes about what we discussed on the payment apps call -- there were concerns (both performance-related and privacy-related) about the proposal as stated. One proposal was that part of app registration could include a lambda function -- required to be a _pure function_ -- that took the filter as input and generated a boolean "I can handle this" as output. These would be evaluated in an isolated context with a null origin (or what specs mean when they say the "origin is a globally unique identifier"), which would prevent external access (addressing the performance concerns) and prevent local storage (which would, in concert with preventing external access, address the privacy concerns).

**Comment by ianbjacobs** [comment]
Adding notes from 19 October app task force discussion:
https://www.w3.org/2016/10/19-apps-minutes.html#filtering
- Need to clarify whether the expectation is that the mediator will still match on the payment method identifier and the payment app will only handle the filter.
- AdamR pointed out that up to now, payment apps have only known about a payment request once selected by the user. But if they are polled for filter matching, this could (depending on how it's proposed), leak information to the app about the existence of a payment request BEFORE the app has been selected.
- Jason points out that some payment apps might implement filtering on the server side, and performance would be a concern.
- AdamR began the thought process of whether a function that returns a boolean about filter matching could be a pure function provided at registration, and that could be run without letting the payment app know.

**Comment by ianbjacobs** [comment]
At the 2 Nov call, Adam Roach took an action to work on the notion of an isolated function:
https://www.w3.org/2016/11/02-apps-minutes.html#item03

**Comment by rsolomakhin** [comment]
> Generate a boolean "I can handle this" as output.

If browser UI is going to be showing payment options from the payment app, then the lambda function should return the subset of its payment options. For example, let's say the payment app registers the following manifest file:

```json
{
  "label": "Bob Pay",
  "options": [{
    "id": "1",
    "label": "Bob Pay Visa",
    "supportedMethods": ["basic-card"]
  }, {
    "id": "2",
    "label": "Bob Pay MasterCard",
    "supportedMethods": ["basic-card"]
  }]
}
```

Then let's say a PaymentRequest like this is constructed:

```javascript
new PaymentRequest(
    [{supportedMethods: ["basic-card"], data: {supportedNetworks: ["visa"]}}],
    shoppingCart)
  .show()
  .then(handlePayment)
  .catch(handleError);
```

If the lambda function returns only "I can handle this" as output, then a browser implementation might show both "Bob Pay Visa" and "Bob Pay MasterCard", which would not be correct. However, if the lambda function returned `["1"]` to indicate that only the first option should be displayed, then the browser can make the correct decision to display only "Bob Pay Visa".

**Comment by rsolomakhin** [comment]
Need some help figuring out how to reconcile `modifiers` here as well. Let's take the same manifest and call PaymentRequest like this:

```javascript
new PaymentRequest(
    [{supportedMethods: ["basic-card"]}}],
    {
      total: {label: "Total", amount: {currency: "USD", value: "100.00"}},
      modifiers: [{
        supportedMethods: ["basic-card"],
        data: {supportedNetworks: "visa"},
        total: {label: "Discounted total", amount: {currency: "USD", value: "99.99"}}
      }]
  })
  .show()
  .then(handlePayment)
  .catch(handleError);
```

Now the browser implementation needs to determine how to show "$99.99" price for "Bob Pay Visa", but "$100.00" price for "Bob Pay MasterCard". I'm not super clear on the best way to accomplish this. I can come up with two options.

**Option 1**: The lambda function should return a mapping from payment option ID to its costs.

```json
{
  "1": {
    "total": {"label": "Discounted total", "amount": {"currency": "USD", "value": "99.99"}},
    "additionalDisplayItems": []
  },
  "2": {
    "total": {"label": "Total", "amount": {"currency": "USD", "value": "100.00"}},
    "additionalDisplayItems": []
  }
}
```

**Option 2**: The lambda function should return a mapping from payment option ID to the index of the applicable modifier. No modifier can be -1.

```json
{"1": 0, "2": -1}
```

First option seems error-prone. I'm certainly more in favor of the second option. Are there better ideas?

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin,

Good comments and observations. It seems like there are two pieces of information the payment app should tell the user agent:

 1) Here are my options that you should display. These are the ones that match given the filter from
     the merchant. So one value returned by the lambda function is a list of option ids.

 2) Here are the relevant parts of the payment request data that you should display in light
    of the match. So a second value returned by the lambda function is some sort of index 
    identifying the matching paymentDetails or paymentDetailsModifiers. 

If I understand your comment correctly, you are suggestion there's a third piece of information:

 3) Here is the mapping of payment request details to payment options. I hadn't thought about
     that before, and still am not sure that's a requirement. 

Please confirm these are the three bits of information you think are necessary for the payment
app to tell the user agent. Thanks!

Ian

**Comment by rsolomakhin** [comment]
The first two pieces of information should be sufficient (options and their matching details/modifiers).

**Comment by ianbjacobs** [comment]
Closing this with the addition of AdamR's lambda function text into the specification
https://www.w3.org/2017/01/04-apps-minutes.html#item03
