### ISSUE TITLE
What does "icon" mean?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#69]
It's a string; not well-defined:
 https://w3c.github.io/webpayments-payment-apps-api/#set-manifest

How is it to be interpreted?

**Comment by ianbjacobs** [comment]
See Web App Manifest definition:
 https://www.w3.org/TR/appmanifest/#icons-member

**Comment by ianbjacobs** [comment]
payment app spec: label, icon
web app manifest: name, icons

It feels like we should align with web app manifest more generally.

**Comment by ianbjacobs** [comment]
Furthermore:

 * There are additional fields (dir, lang) that also likely apply.
 * There's an algorithm that describes how to handle multiple icons:
   https://www.w3.org/TR/appmanifest/#dfn-steps-for-processing-an-array-of-images

Proposed:

 * Delete the current definitions of label and icon
 * Specify that all the members of the manifest that are defined in section 8 are available, and their meaning is defined in Web App Manifest.

**Comment by marcoscaceres** [comment]
> There are additional fields (dir, lang) that also likely apply.

Dir and lang only apply to text that is presented to users. 

I need to check what you are trying to achieve here in more detail - I'm still working my way through the PaymentRequest spec.

**Comment by ianbjacobs** [comment]
We discussed 4 April:
 https://www.w3.org/2017/04/04-apps-minutes#item07

We resolved to close this issue in light of where we have gotten to with the spec, and to open a more narrow issue on the missing definition of "image object" (citing Web App Manifest).
