### ISSUE TITLE
Split out enabled and supported methods

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#7]
Raised at London face 2 face and migrated from: https://github.com/w3c/webpayments/issues/158

To answer @ianbjacobs question on that thread:

I understand the desire is to allow payment apps to differentiate the between the methods they support (but require an enrollment flow to use) and those hat are enabled (supported and user has already enrolled)

**Comment by ianbjacobs** [comment]
I think this is no longer pertinent here.
