### ISSUE TITLE
“Security Error” on different origins

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#9]
Migrated from https://github.com/w3c/webpayments/issues/157 by @LaurentCastillo 

The current spec mention a “Security Error” on different origins when invoking a payment app. It might prevent registering localhost payment apps (which was one of the method mentioned to invoke local native apps). Is it a feature we want to keep?

**Comment by ianbjacobs** [comment]
The payment app spec depends on "Secure Contexts" [1] which considers 127.0.0.1 a "potentially trustworthy" origin.

I suggest we close this issue for now. We have not yet addressed management of native payment apps and it may come up again in that detailed context.

[1] https://www.w3.org/TR/secure-contexts/
[2] https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy

**Comment by ianbjacobs** [comment]
Closing this issue for now. When we get to native apps we may revisit it.

Ian
